<a href="https://colab.research.google.com/github/aditi1295/MachineLearning/blob/main/optuna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-5.0.0-py3-none-any.whl.metadata (14 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.5)
Downloading optuna-5.0.0-py3-none-any.whl (442 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 8.2 MB/s eta 0:00:00
Downloading alembic-1.20.0-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 22.8 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.20.0 colorlog-6.12.0 optuna-5.0.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-09-18 14:34:41,843] A new study created in memory with name: no-name-82a7f64f-1938-4bf3-aaca-f6e77580d74e
[I 2026-09-18 14:34:43,314] Trial 0 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:44,684] Trial 1 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:45,925] Trial 2 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 55, 'max_depth': 17}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:47,999] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 84, 'max_depth': 19}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:49,112] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 85, 'max_depth': 5}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:51,267] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 12}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:52,400] Trial 6 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 16}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:53,692] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 16}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:54,947] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 118, 'max_depth': 9}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:57,137] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 181, 'max_depth': 10}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:57,733] Trial 10 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 55, 'max_depth': 6}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:34:59,410] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 16}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:00,811] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 20}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:01,806] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 116, 'max_depth': 13}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:02,878] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 183, 'max_depth': 17}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:03,361] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 14}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:04,197] Trial 16 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 163, 'max_depth': 4}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:04,824] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 19}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:05,784] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 166, 'max_depth': 14}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:06,571] Trial 19 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 133, 'max_depth': 18}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:07,140] Trial 20 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 91, 'max_depth': 10}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:07,935] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 18}. Best is trial 0 with value: 0.7802607076350093.
[I 2026-09-18 14:35:09,079] Trial 22 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 197, 'max_depth': 19}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:10,246] Trial 23 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 199, 'max_depth': 17}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:10,654] Trial 24 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 65, 'max_depth': 20}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:11,868] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 191, 'max_depth': 20}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:13,407] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 20}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:14,883] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 176, 'max_depth': 15}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:15,956] Trial 28 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 183, 'max_depth': 13}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:17,614] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 18}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:19,729] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 14}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:21,165] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:21,714] Trial 32 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 54, 'max_depth': 16}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:23,016] Trial 33 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 115, 'max_depth': 17}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:24,168] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 152, 'max_depth': 18}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:25,179] Trial 35 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:25,857] Trial 36 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 71, 'max_depth': 18}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:26,521] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 66, 'max_depth': 18}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:27,855] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 162, 'max_depth': 10}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:28,457] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 12}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:29,115] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:29,801] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 116, 'max_depth': 20}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:30,238] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 71, 'max_depth': 16}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:31,181] Trial 43 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 17}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:31,810] Trial 44 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 72, 'max_depth': 12}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:32,443] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 56, 'max_depth': 14}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:33,176] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:34,738] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 15}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:35,547] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 7}. Best is trial 22 with value: 0.7821229050279329.
[I 2026-09-18 14:35:37,471] Trial 49 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 197, 'max_depth': 4}. Best is trial 22 with value: 0.7821229050279329.

In [7]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 197, 'max_depth': 19}

In [8]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

#Samplers in Optuna

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-09-18 14:36:00,068] A new study created in memory with name: no-name-03a0581a-be7a-4aa3-8561-3231ca88bbdc
[I 2026-09-18 14:36:00,603] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 9}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-09-18 14:36:01,994] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 140, 'max_depth': 9}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-09-18 14:36:03,042] Trial 2 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 107, 'max_depth': 3}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-09-18 14:36:05,870] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 176, 'max_depth': 5}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-09-18 14:36:06,572] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 53, 'max_depth': 16}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-09-18 14:36:07,486] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-09-18 14:36:07,970] Trial 6 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 17}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-09-18 14:36:08,382] Trial 7 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 69, 'max_depth': 18}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:09,082] Trial 8 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 136, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:09,804] Trial 9 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 128, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:10,744] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 161, 'max_depth': 19}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:11,483] Trial 11 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:12,424] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 161, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:12,849] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 6}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:13,297] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 76, 'max_depth': 13}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:14,394] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 194, 'max_depth': 8}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:15,451] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:16,090] Trial 17 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 109, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:17,509] Trial 18 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 108, 'max_depth': 4}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:18,015] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 55, 'max_depth': 6}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:20,251] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 6}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:21,601] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 82, 'max_depth': 12}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:23,204] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:23,871] Trial 23 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 54, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:24,779] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 78, 'max_depth': 12}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:25,872] Trial 25 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 93, 'max_depth': 12}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:28,212] Trial 26 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 185, 'max_depth': 6}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:29,083] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 123, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:30,025] Trial 28 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 155, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:33,142] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 160, 'max_depth': 8}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:34,271] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 7}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:35,222] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 79, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:37,219] Trial 32 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 177, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:38,089] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:40,814] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 183, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:41,928] Trial 35 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 94, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:44,877] Trial 36 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 154, 'max_depth': 8}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:47,675] Trial 37 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:49,759] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 136, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:51,998] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 11}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:54,269] Trial 40 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 186, 'max_depth': 3}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:54,986] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 19}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:36:57,567] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:00,986] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 197, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:02,257] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 137, 'max_depth': 5}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:03,939] Trial 45 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 181, 'max_depth': 5}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:04,745] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 10}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:05,804] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 183, 'max_depth': 19}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:06,351] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 14}. Best is trial 7 with value: 0.7783985102420857.
[I 2026-09-18 14:37:07,468] Trial 49 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 194, 'max_depth': 17}. Best is trial 49 with value: 0.7802607076350093.

In [11]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 194, 'max_depth': 17}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-09-18 14:37:13,184] A new study created in memory with name: no-name-257f2bd3-081b-4402-b3e3-bf3b9aa609d6
[I 2026-09-18 14:37:14,055] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-09-18 14:37:15,632] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-09-18 14:37:16,244] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:17,345] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:18,477] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:18,871] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:19,681] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:20,557] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:21,451] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:22,698] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:24,588] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:26,906] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:28,795] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-18 14:37:29,351] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-09-18 14:37:30,426] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-09-18 14:37:30,825] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

#oputna visualization

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# 3. Slice Plot
plot_slice(study).show()

In [21]:
# 4. Contour Plot
plot_contour(study).show()

In [22]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

#Optimizing Multiple ML Models

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [25]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-09-18 14:40:04,462] A new study created in memory with name: no-name-f0558af1-0abd-48a8-aeac-7d1abcbef929
[I 2026-09-18 14:40:04,493] Trial 0 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.6753684914304938, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.7392923649906891.
[I 2026-09-18 14:40:04,566] Trial 1 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.652318502795119, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:04,606] Trial 2 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.19196354403392138, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:04,654] Trial 3 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 88.68808120095807, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:07,129] Trial 4 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 66, 'learning_rate': 0.030035434763471723, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:09,568] Trial 5 finished with value: 0.6945996275605214 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 139, 'learning_rate': 0.21720117517373286, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:11,256] Trial 6 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 221, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:11,288] Trial 7 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4992929383904776, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:11,974] Trial 8 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 58, 'learning_rate': 0.19881042336296756, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:12,121] Trial 9 finished with value: 0.7094972067039107 and parameters: {'classifier': 'SVM', 'C': 32.14952902933402, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:13,921] Trial 10 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:13,984] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.200942976427512, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:14,072] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.369020971395145, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:14,153] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.314814124752477, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:14,213] Trial 14 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 8.358894835467495, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:16,691] Trial 15 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 176, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:16,756] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.898644600548305, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:17,039] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.750302179186114, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:20,413] Trial 18 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 292, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:24,768] Trial 19 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 133, 'learning_rate': 0.011104037702100373, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:24,848] Trial 20 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 2.630947547373829, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:25,016] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.869601724695132, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:25,096] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.842151891720823, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:25,262] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 22.491943989324973, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 1 with value: 0.7858472998137801.
[I 2026-09-18 14:40:25,349] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6997110141547275, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 24 with value: 0.7858472998137803.
[I 2026-09-18 14:40:25,451] Trial 25 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.4531679097737425, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 24 with value: 0.7858472998137803.
[I 2026-09-18 14:40:25,541] Trial 26 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10104176211239906, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 26 with value: 0.7877094972067038.
[I 2026-09-18 14:40:25,589] Trial 27 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12582675083427006, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:32,484] Trial 28 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 248, 'learning_rate': 0.055165495744090444, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,069] Trial 29 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 104, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,122] Trial 30 finished with value: 0.7430167597765363 and parameters: {'classifier': 'SVM', 'C': 0.1167492786300016, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,175] Trial 31 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25716178117466854, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,223] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27900623359043386, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,279] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10572128657758406, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,348] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1066266714431536, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,391] Trial 35 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.11269469831778345, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,421] Trial 36 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1028920449415426, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:33,451] Trial 37 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1921326140018931, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,181] Trial 38 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 207, 'learning_rate': 0.058082357187867334, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,230] Trial 39 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.173333197573327, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,277] Trial 40 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.360131659675186, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,339] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10549926452451092, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,392] Trial 42 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.1540683577697731, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,494] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5957996976621197, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:38,541] Trial 44 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10672450734260858, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:39,791] Trial 45 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 171, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:39,825] Trial 46 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.21831559260108543, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,617] Trial 47 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 259, 'learning_rate': 0.012553470268671006, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,664] Trial 48 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1684309884074128, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,720] Trial 49 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.3572467443868494, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,766] Trial 50 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14583073027650326, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,811] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15004523517006488, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,856] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14840522842419587, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,901] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16749264540132675, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:41,949] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25651638606018357, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:42,732] Trial 55 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 99, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:42,781] Trial 56 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.15625412320397686, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:42,828] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.33106034013636987, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,734] Trial 58 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 190, 'learning_rate': 0.09849870183404644, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,772] Trial 59 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.8320880801961758, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,802] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14635137781155744, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,832] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1453127095086101, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,861] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14970188387044886, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,891] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22292794297918736, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,921] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14779224473383482, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:45,952] Trial 65 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4374640170453799, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,368] Trial 66 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 265, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,398] Trial 67 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1430537991690785, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,427] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21656750172504136, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,461] Trial 69 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 83.12954504027878, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,497] Trial 70 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.2927240180081643, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,526] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1419023131510578, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,555] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1478124211388386, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,585] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23450975267596577, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,616] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13462984505640338, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:47,646] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1943441124503885, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,087] Trial 76 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 147, 'learning_rate': 0.03290515608403284, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,118] Trial 77 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1315776140248911, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,148] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2097783411235548, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,180] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4772298783930201, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,631] Trial 80 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 87, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 27 with value: 0.7895716945996275.
[I 2026-09-18 14:40:49,661] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1399414739941349, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12582675083427006, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,system_attrs_tpe:relative_params:0,state
0,0,0.739292,2026-09-18 14:40:04.463606,2026-09-18 14:40:04.493309,0 days 00:00:00.029703,0.675368,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.785847,2026-09-18 14:40:04.494889,2026-09-18 14:40:04.566532,0 days 00:00:00.071643,12.652319,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.716946,2026-09-18 14:40:04.567628,2026-09-18 14:40:04.606710,0 days 00:00:00.039082,0.191964,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.696462,2026-09-18 14:40:04.608215,2026-09-18 14:40:04.654008,0 days 00:00:00.045793,88.688081,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.737430,2026-09-18 14:40:04.655218,2026-09-18 14:40:07.129519,0 days 00:00:02.474301,NaN,NaN,GradientBoosting,NaN,NaN,0.030035,19.0,2.0,7.0,66.0,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.759777,2026-09-18 14:40:55.655568,2026-09-18 14:40:55.793617,0 days 00:00:00.138049,0.254394,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
96,96,0.787709,2026-09-18 14:40:55.800007,2026-09-18 14:40:55.907899,0 days 00:00:00.107892,0.156323,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
97,97,0.787709,2026-09-18 14:40:55.910972,2026-09-18 14:40:55.981035,0 days 00:00:00.070063,0.101992,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
98,98,0.785847,2026-09-18 14:40:55.985343,2026-09-18 14:40:56.077764,0 days 00:00:00.092421,0.198483,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
99,99,0.761639,2026-09-18 14:40:56.084358,2026-09-18 14:40:57.741135,0 days 00:00:01.656777,NaN,True,RandomForest,NaN,NaN,NaN,18.0,4.0,3.0,120.0,"{""classifier"": ""RandomForest""}",COMPLETE

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 80
GradientBoosting    10
RandomForest        10
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.738361
RandomForest        0.765363
SVM                 0.775489
Name: value, dtype: float64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [42]:
!pip install -U "optuna-integration[xgboost]"
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")
    # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-5.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (5.0.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (3.4.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (1.20.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (2.31.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.5)
Downloading optuna_integration-5.0.0-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 2.7 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-5.0.0

[I 2026-09-18 14:49:10,681] A new study created in memory with name: no-name-e390facf-84f2-43a8-bbbd-8482fa1c5be8

[0]	train-mlogloss:0.95868	eval-mlogloss:0.95081
[1]	train-mlogloss:0.82619	eval-mlogloss:0.81177
[2]	train-mlogloss:0.71630	eval-mlogloss:0.69394
[3]	train-mlogloss:0.63170	eval-mlogloss:0.61056
[4]	train-mlogloss:0.55507	eval-mlogloss:0.53094
[5]	train-mlogloss:0.49597	eval-mlogloss:0.46842
[6]	train-mlogloss:0.44505	eval-mlogloss:0.41469
[7]	train-mlogloss:0.41083	eval-mlogloss:0.38179
[8]	train-mlogloss:0.37061	eval-mlogloss:0.33696
[9]	train-mlogloss:0.33396	eval-mlogloss:0.29685
[10]	train-mlogloss:0.30113	eval-mlogloss:0.26094
[11]	train-mlogloss:0.27327	eval-mlogloss:0.23301
[12]	train-mlogloss:0.25302	eval-mlogloss:0.21171
[13]	train-mlogloss:0.23464	eval-mlogloss:0.19445
[14]	train-mlogloss:0.21379	eval-mlogloss:0.17373
[15]	train-mlogloss:0.19713	eval-mlogloss:0.15504
[16]	train-mlogloss:0.18207	eval-mlogloss:0.13756
[17]	train-mlogloss:0.16859	eval-mlogloss:0.12319
[18]	train-mlogloss:0.15607	eval-mlogloss:0.11178
[19]	train-mlogloss:0.14721	eval-mlogloss:0.10429
[20]	train-mlogloss:0.13576	eval-mlogloss:0.09732
[21]	train-mlogloss:0.12794	eval-mlogloss:0.08953
[22]	train-mlogloss:0.12300	eval-mlogloss:0.08368
[23]	train-mlogloss:0.11677	eval-mlogloss:0.07869
[24]	train-mlogloss:0.11235	eval-mlogloss:0.07304
[25]	train-mlogloss:0.10714	eval-mlogloss:0.06684
[26]	train-mlogloss:0.10306	eval-mlogloss:0.06125
[27]	train-mlogloss:0.09967	eval-mlogloss:0.05636
[28]	train-mlogloss:0.09721	eval-mlogloss:0.05388
[29]	train-mlogloss:0.09567	eval-mlogloss:0.05169
[30]	train-mlogloss:0.09501	eval-mlogloss:0.05171
[31]	train-mlogloss:0.09342	eval-mlogloss:0.04950
[32]	train-mlogloss:0.09252	eval-mlogloss:0.04765
[33]	train-mlogloss:0.09263	eval-mlogloss:0.04810
[34]	train-mlogloss:0.09169	eval-mlogloss:0.04722
[35]	train-mlogloss:0.09118	eval-mlogloss:0.04621
[36]	train-mlogloss:0.09068	eval-mlogloss:0.04475
[37]	train-mlogloss:0.08973	eval-mlogloss:0.04308
[38]	train-mlogloss:0.08781	eval-mlogloss:0.04098
[39]	train-mlogloss:0.08707	eval-mlogloss:0.04084
[40]	train-mlogloss:0.08636	eval-mlogloss:0.04182
[41]	train-mlogloss:0.08584	eval-mlogloss:0.04233
[42]	train-mlogloss:0.08519	eval-mlogloss:0.04248
[43]	train-mlogloss:0.08480	eval-mlogloss:0.04362
[44]	train-mlogloss:0.08443	eval-mlogloss:0.04476
[45]	train-mlogloss:0.08337	eval-mlogloss:0.04310
[46]	train-mlogloss:0.08291	eval-mlogloss:0.04362
[47]	train-mlogloss:0.08247	eval-mlogloss:0.04327
[48]	train-mlogloss:0.08240	eval-mlogloss:0.04299
[49]	train-mlogloss:0.08121	eval-mlogloss:0.04152
[50]	train-mlogloss:0.08087	eval-mlogloss:0.04090
[51]	train-mlogloss:0.08028	eval-mlogloss:0.03957
[52]	train-mlogloss:0.07989	eval-mlogloss:0.03939
[53]	train-mlogloss:0.07906	eval-mlogloss:0.03893
[54]	train-mlogloss:0.07916	eval-mlogloss:0.03829
[55]	train-mlogloss:0.07841	eval-mlogloss:0.03720
[56]	train-mlogloss:0.07836	eval-mlogloss:0.03729
[57]	train-mlogloss:0.07775	eval-mlogloss:0.03764
[58]	train-mlogloss:0.07727	eval-mlogloss:0.03762
[59]	train-mlogloss:0.07738	eval-mlogloss:0.03796
[60]	train-mlogloss:0.07724	eval-mlogloss:0.03709
[61]	train-mlogloss:0.07649	eval-mlogloss:0.03748

/usr/lib/python3.13/importlib/__init__.py:88: FutureWarning:

`optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.

[62]	train-mlogloss:0.07606	eval-mlogloss:0.03720
[63]	train-mlogloss:0.07588	eval-mlogloss:0.03681
[64]	train-mlogloss:0.07575	eval-mlogloss:0.03696
[65]	train-mlogloss:0.07545	eval-mlogloss:0.03684
[66]	train-mlogloss:0.07519	eval-mlogloss:0.03561
[67]	train-mlogloss:0.07483	eval-mlogloss:0.03498
[68]	train-mlogloss:0.07484	eval-mlogloss:0.03508
[69]	train-mlogloss:0.07482	eval-mlogloss:0.03450
[70]	train-mlogloss:0.07448	eval-mlogloss:0.03517
[71]	train-mlogloss:0.07434	eval-mlogloss:0.03545
[72]	train-mlogloss:0.07370	eval-mlogloss:0.03426
[73]	train-mlogloss:0.07348	eval-mlogloss:0.03367
[74]	train-mlogloss:0.07349	eval-mlogloss:0.03347
[75]	train-mlogloss:0.07325	eval-mlogloss:0.03312
[76]	train-mlogloss:0.07303	eval-mlogloss:0.03310
[77]	train-mlogloss:0.07306	eval-mlogloss:0.03245
[78]	train-mlogloss:0.07316	eval-mlogloss:0.03213
[79]	train-mlogloss:0.07249	eval-mlogloss:0.03100
[80]	train-mlogloss:0.07232	eval-mlogloss:0.03084
[81]	train-mlogloss:0.07217	eval-mlogloss:0.03104
[82]	train-mlogloss:0.07214	eval-mlogloss:0.03154
[83]	train-mlogloss:0.07168	eval-mlogloss:0.03094
[84]	train-mlogloss:0.07128	eval-mlogloss:0.03248
[85]	train-mlogloss:0.07119	eval-mlogloss:0.03212
[86]	train-mlogloss:0.07098	eval-mlogloss:0.03192
[87]	train-mlogloss:0.07069	eval-mlogloss:0.03312
[88]	train-mlogloss:0.07073	eval-mlogloss:0.03265
[89]	train-mlogloss:0.07070	eval-mlogloss:0.03325
[90]	train-mlogloss:0.07033	eval-mlogloss:0.03254
[91]	train-mlogloss:0.07030	eval-mlogloss:0.03243
[92]	train-mlogloss:0.07005	eval-mlogloss:0.03164
[93]	train-mlogloss:0.06996	eval-mlogloss:0.03136
[94]	train-mlogloss:0.06986	eval-mlogloss:0.03160
[95]	train-mlogloss:0.06978	eval-mlogloss:0.03161
[96]	train-mlogloss:0.06945	eval-mlogloss:0.03075
[97]	train-mlogloss:0.06921	eval-mlogloss:0.03073
[98]	train-mlogloss:0.06895	eval-mlogloss:0.03116
[99]	train-mlogloss:0.06889	eval-mlogloss:0.03111
[100]	train-mlogloss:0.06859	eval-mlogloss:0.03146
[101]	train-mlogloss:0.06841	eval-mlogloss:0.03153
[102]	train-mlogloss:0.06820	eval-mlogloss:0.03151
[103]	train-mlogloss:0.06797	eval-mlogloss:0.03221
[104]	train-mlogloss:0.06792	eval-mlogloss:0.03182
[105]	train-mlogloss:0.06757	eval-mlogloss:0.03145
[106]	train-mlogloss:0.06741	eval-mlogloss:0.03036
[107]	train-mlogloss:0.06726	eval-mlogloss:0.03032
[108]	train-mlogloss:0.06728	eval-mlogloss:0.03016
[109]	train-mlogloss:0.06701	eval-mlogloss:0.03026
[110]	train-mlogloss:0.06682	eval-mlogloss:0.03013
[111]	train-mlogloss:0.06683	eval-mlogloss:0.03048
[112]	train-mlogloss:0.06669	eval-mlogloss:0.03046
[113]	train-mlogloss:0.06660	eval-mlogloss:0.03036
[114]	train-mlogloss:0.06662	eval-mlogloss:0.03059
[115]	train-mlogloss:0.06634	eval-mlogloss:0.02983
[116]	train-mlogloss:0.06632	eval-mlogloss:0.03022
[117]	train-mlogloss:0.06622	eval-mlogloss:0.03041
[118]	train-mlogloss:0.06627	eval-mlogloss:0.03098
[119]	train-mlogloss:0.06611	eval-mlogloss:0.03065
[120]	train-mlogloss:0.06603	eval-mlogloss:0.02999
[121]	train-mlogloss:0.06586	eval-mlogloss:0.03024
[122]	train-mlogloss:0.06583	eval-mlogloss:0.03013
[123]	train-mlogloss:0.06575	eval-mlogloss:0.03025
[124]	train-mlogloss:0.06567	eval-mlogloss:0.03020
[125]	train-mlogloss:0.06556	eval-mlogloss:0.02981
[126]	train-mlogloss:0.06553	eval-mlogloss:0.02969
[127]	train-mlogloss:0.06548	eval-mlogloss:0.02992
[128]	train-mlogloss:0.06565	eval-mlogloss:0.03081
[129]	train-mlogloss:0.06569	eval-mlogloss:0.03050
[130]	train-mlogloss:0.06558	eval-mlogloss:0.03039
[131]	train-mlogloss:0.06531	eval-mlogloss:0.03023
[132]	train-mlogloss:0.06529	eval-mlogloss:0.02985
[133]	train-mlogloss:0.06539	eval-mlogloss:0.02964
[134]	train-mlogloss:0.06534	eval-mlogloss:0.02959
[135]	train-mlogloss:0.06531	eval-mlogloss:0.02963
[136]	train-mlogloss:0.06511	eval-mlogloss:0.03024
[137]	train-mlogloss:0.06510	eval-mlogloss:0.03001
[138]	train-mlogloss:0.06502	eval-mlogloss:0.03039
[139]	train-mlogloss:0.06499	eval-mlogloss:0.02996
[140]	train-mlogloss:0.06495	eval-mlogloss:0.02972
[141]	train-mlogloss:0.06491	eval-mlogloss:0.03003
[142]	train-mlogloss:0.06475	eval-mlogloss:0.02967
[143]	train-mlogloss:0.06468	eval-mlogloss:0.02955
[144]	train-mlogloss:0.06438	eval-mlogloss:0.02991
[145]	train-mlogloss:0.06432	eval-mlogloss:0.02962
[146]	train-mlogloss:0.06427	eval-mlogloss:0.02990
[147]	train-mlogloss:0.06419	eval-mlogloss:0.03043
[148]	train-mlogloss:0.06411	eval-mlogloss:0.03028
[149]	train-mlogloss:0.06408	eval-mlogloss:0.02979
[150]	train-mlogloss:0.06381	eval-mlogloss:0.02932
[151]	train-mlogloss:0.06367	eval-mlogloss:0.02827
[152]	train-mlogloss:0.06359	eval-mlogloss:0.02820
[153]	train-mlogloss:0.06346	eval-mlogloss:0.02839
[154]	train-mlogloss:0.06352	eval-mlogloss:0.02790
[155]	train-mlogloss:0.06350	eval-mlogloss:0.02808
[156]	train-mlogloss:0.06344	eval-mlogloss:0.02788
[157]	train-mlogloss:0.06347	eval-mlogloss:0.02757
[158]	train-mlogloss:0.06349	eval-mlogloss:0.02791
[159]	train-mlogloss:0.06321	eval-mlogloss:0.02718
[160]	train-mlogloss:0.06322	eval-mlogloss:0.02722
[161]	train-mlogloss:0.06319	eval-mlogloss:0.02721
[162]	train-mlogloss:0.06329	eval-mlogloss:0.02795
[163]	train-mlogloss:0.06316	eval-mlogloss:0.02894
[164]	train-mlogloss:0.06317	eval-mlogloss:0.02899
[165]	train-mlogloss:0.06314	eval-mlogloss:0.02881
[166]	train-mlogloss:0.06278	eval-mlogloss:0.02891
[167]	train-mlogloss:0.06276	eval-mlogloss:0.02853
[168]	train-mlogloss:0.06274	eval-mlogloss:0.02853
[169]	train-mlogloss:0.06270	eval-mlogloss:0.02785
[170]	train-mlogloss:0.06246	eval-mlogloss:0.02766
[171]	train-mlogloss:0.06244	eval-mlogloss:0.02774
[172]	train-mlogloss:0.06227	eval-mlogloss:0.02703
[173]	train-mlogloss:0.06225	eval-mlogloss:0.02688
[174]	train-mlogloss:0.06214	eval-mlogloss:0.02662
[175]	train-mlogloss:0.06217	eval-mlogloss:0.02626
[176]	train-mlogloss:0.06209	eval-mlogloss:0.02644
[177]	train-mlogloss:0.06198	eval-mlogloss:0.02612
[178]	train-mlogloss:0.06193	eval-mlogloss:0.02565
[179]	train-mlogloss:0.06180	eval-mlogloss:0.02560
[180]	train-mlogloss:0.06183	eval-mlogloss:0.02560
[181]	train-mlogloss:0.06190	eval-mlogloss:0.02556
[182]	train-mlogloss:0.06193	eval-mlogloss:0.02551
[183]	train-mlogloss:0.06184	eval-mlogloss:0.02556
[184]	train-mlogloss:0.06165	eval-mlogloss:0.02553
[185]	train-mlogloss:0.06173	eval-mlogloss:0.02545
[186]	train-mlogloss:0.06162	eval-mlogloss:0.02566
[187]	train-mlogloss:0.06162	eval-mlogloss:0.02539
[188]	train-mlogloss:0.06178	eval-mlogloss:0.02562
[189]	train-mlogloss:0.06186	eval-mlogloss:0.02538
[190]	train-mlogloss:0.06201	eval-mlogloss:0.02538
[191]	train-mlogloss:0.06190	eval-mlogloss:0.02573
[192]	train-mlogloss:0.06184	eval-mlogloss:0.02581
[193]	train-mlogloss:0.06180	eval-mlogloss:0.02591
[194]	train-mlogloss:0.06164	eval-mlogloss:0.02596
[195]	train-mlogloss:0.06172	eval-mlogloss:0.02546
[196]	train-mlogloss:0.06168	eval-mlogloss:0.02497
[197]	train-mlogloss:0.06150	eval-mlogloss:0.02494
[198]	train-mlogloss:0.06158	eval-mlogloss:0.02504
[199]	train-mlogloss:0.06143	eval-mlogloss:0.02576
[200]	train-mlogloss:0.06134	eval-mlogloss:0.02499
[201]	train-mlogloss:0.06118	eval-mlogloss:0.02513
[202]	train-mlogloss:0.06116	eval-mlogloss:0.02520
[203]	train-mlogloss:0.06118	eval-mlogloss:0.02518
[204]	train-mlogloss:0.06094	eval-mlogloss:0.02554
[205]	train-mlogloss:0.06092	eval-mlogloss:0.02481
[206]	train-mlogloss:0.06096	eval-mlogloss:0.02545
[207]	train-mlogloss:0.06068	eval-mlogloss:0.02559
[208]	train-mlogloss:0.06069	eval-mlogloss:0.02564
[209]	train-mlogloss:0.06067	eval-mlogloss:0.02560
[210]	train-mlogloss:0.06070	eval-mlogloss:0.02565
[211]	train-mlogloss:0.06072	eval-mlogloss:0.02585
[212]	train-mlogloss:0.06078	eval-mlogloss:0.02644
[213]	train-mlogloss:0.06065	eval-mlogloss:0.02614
[214]	train-mlogloss:0.06065	eval-mlogloss:0.02630
[215]	train-mlogloss:0.06050	eval-mlogloss:0.02571
[216]	train-mlogloss:0.06050	eval-mlogloss:0.02578
[217]	train-mlogloss:0.06037	eval-mlogloss:0.02579
[218]	train-mlogloss:0.06034	eval-mlogloss:0.02591
[219]	train-mlogloss:0.06018	eval-mlogloss:0.02524
[220]	train-mlogloss:0.06018	eval-mlogloss:0.02514
[221]	train-mlogloss:0.06017	eval-mlogloss:0.02476
[222]	train-mlogloss:0.06014	eval-mlogloss:0.02447
[223]	train-mlogloss:0.06013	eval-mlogloss:0.02441
[224]	train-mlogloss:0.06012	eval-mlogloss:0.02450
[225]	train-mlogloss:0.06008	eval-mlogloss:0.02471
[226]	train-mlogloss:0.06009	eval-mlogloss:0.02465
[227]	train-mlogloss:0.06008	eval-mlogloss:0.02457
[228]	train-mlogloss:0.06001	eval-mlogloss:0.02444
[229]	train-mlogloss:0.05996	eval-mlogloss:0.02450
[230]	train-mlogloss:0.06002	eval-mlogloss:0.02534
[231]	train-mlogloss:0.05985	eval-mlogloss:0.02574
[232]	train-mlogloss:0.05986	eval-mlogloss:0.02603
[233]	train-mlogloss:0.05972	eval-mlogloss:0.02555
[234]	train-mlogloss:0.05973	eval-mlogloss:0.02561
[235]	train-mlogloss:0.05972	eval-mlogloss:0.02595
[236]	train-mlogloss:0.05971	eval-mlogloss:0.02527
[237]	train-mlogloss:0.05970	eval-mlogloss:0.02541
[238]	train-mlogloss:0.05958	eval-mlogloss:0.02568
[239]	train-mlogloss:0.05957	eval-mlogloss:0.02573
[240]	train-mlogloss:0.05957	eval-mlogloss:0.02559
[241]	train-mlogloss:0.05954	eval-mlogloss:0.02563
[242]	train-mlogloss:0.05951	eval-mlogloss:0.02563
[243]	train-mlogloss:0.05942	eval-mlogloss:0.02484
[244]	train-mlogloss:0.05943	eval-mlogloss:0.02489
[245]	train-mlogloss:0.05939	eval-mlogloss:0.02478
[246]	train-mlogloss:0.05928	eval-mlogloss:0.02494
[247]	train-mlogloss:0.05928	eval-mlogloss:0.02556
[248]	train-mlogloss:0.05935	eval-mlogloss:0.02520
[249]	train-mlogloss:0.05933	eval-mlogloss:0.02520
[250]	train-mlogloss:0.05932	eval-mlogloss:0.02502
[251]	train-mlogloss:0.05932	eval-mlogloss:0.02498
[252]	train-mlogloss:0.05924	eval-mlogloss:0.02480
[253]	train-mlogloss:0.05927	eval-mlogloss:0.02454

[I 2026-09-18 14:49:11,397] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.00432232676269759, 'alpha': 1.7219063672366305e-05, 'eta': 0.12831722446825466, 'gamma': 0.00015260127947542152, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6695314840050257, 'colsample_bytree': 0.7364141600688288}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.99111	eval-mlogloss:0.98605
[1]	train-mlogloss:0.87282	eval-mlogloss:0.86090
[2]	train-mlogloss:0.77585	eval-mlogloss:0.75911
[3]	train-mlogloss:0.69985	eval-mlogloss:0.67831
[4]	train-mlogloss:0.62919	eval-mlogloss:0.60234
[5]	train-mlogloss:0.57244	eval-mlogloss:0.54314
[6]	train-mlogloss:0.52332	eval-mlogloss:0.49130
[7]	train-mlogloss:0.48895	eval-mlogloss:0.45675
[8]	train-mlogloss:0.44829	eval-mlogloss:0.41113
[9]	train-mlogloss:0.41150	eval-mlogloss:0.37144
[10]	train-mlogloss:0.37671	eval-mlogloss:0.33347
[11]	train-mlogloss:0.34727	eval-mlogloss:0.30241
[12]	train-mlogloss:0.32490	eval-mlogloss:0.27916
[13]	train-mlogloss:0.30571	eval-mlogloss:0.25984
[14]	train-mlogloss:0.28276	eval-mlogloss:0.23574
[15]	train-mlogloss:0.26296	eval-mlogloss:0.21381
[16]	train-mlogloss:0.24521	eval-mlogloss:0.19371
[17]	train-mlogloss:0.22861	eval-mlogloss:0.17664
[18]	train-mlogloss:0.21495	eval-mlogloss:0.16325
[19]	train-mlogloss:0.20371	eval-mlogloss:0.15292
[20]	train-mlogloss:0.19099	eval-mlogloss:0.14296
[21]	train-mlogloss:0.17982	eval-mlogloss:0.13090
[22]	train-mlogloss:0.17348	eval-mlogloss:0.12498
[23]	train-mlogloss:0.16530	eval-mlogloss:0.11595
[24]	train-mlogloss:0.15860	eval-mlogloss:0.10911
[25]	train-mlogloss:0.15133	eval-mlogloss:0.10110
[26]	train-mlogloss:0.14400	eval-mlogloss:0.09104
[27]	train-mlogloss:0.13893	eval-mlogloss:0.08671
[28]	train-mlogloss:0.13393	eval-mlogloss:0.08197
[29]	train-mlogloss:0.13026	eval-mlogloss:0.07732
[30]	train-mlogloss:0.12835	eval-mlogloss:0.07634
[31]	train-mlogloss:0.12642	eval-mlogloss:0.07362
[32]	train-mlogloss:0.12352	eval-mlogloss:0.06939
[33]	train-mlogloss:0.12154	eval-mlogloss:0.06880
[34]	train-mlogloss:0.12002	eval-mlogloss:0.06683
[35]	train-mlogloss:0.11740	eval-mlogloss:0.06497
[36]	train-mlogloss:0.11692	eval-mlogloss:0.06394
[37]	train-mlogloss:0.11470	eval-mlogloss:0.06057
[38]	train-mlogloss:0.11186	eval-mlogloss:0.05778
[39]	train-mlogloss:0.11175	eval-mlogloss:0.05770
[40]	train-mlogloss:0.11095	eval-mlogloss:0.05733
[41]	train-mlogloss:0.11077	eval-mlogloss:0.05728
[42]	train-mlogloss:0.10949	eval-mlogloss:0.05567
[43]	train-mlogloss:0.10866	eval-mlogloss:0.05438
[44]	train-mlogloss:0.10801	eval-mlogloss:0.05498
[45]	train-mlogloss:0.10671	eval-mlogloss:0.05263
[46]	train-mlogloss:0.10594	eval-mlogloss:0.05325
[47]	train-mlogloss:0.10518	eval-mlogloss:0.05201
[48]	train-mlogloss:0.10485	eval-mlogloss:0.05151
[49]	train-mlogloss:0.10371	eval-mlogloss:0.04987
[50]	train-mlogloss:0.10340	eval-mlogloss:0.05022
[51]	train-mlogloss:0.10305	eval-mlogloss:0.04927
[52]	train-mlogloss:0.10299	eval-mlogloss:0.04878
[53]	train-mlogloss:0.10191	eval-mlogloss:0.04771
[54]	train-mlogloss:0.10151	eval-mlogloss:0.04732
[55]	train-mlogloss:0.10053	eval-mlogloss:0.04593
[56]	train-mlogloss:0.10038	eval-mlogloss:0.04574
[57]	train-mlogloss:0.09984	eval-mlogloss:0.04595
[58]	train-mlogloss:0.09922	eval-mlogloss:0.04623
[59]	train-mlogloss:0.09901	eval-mlogloss:0.04594
[60]	train-mlogloss:0.09843	eval-mlogloss:0.04488
[61]	train-mlogloss:0.09744	eval-mlogloss:0.04533
[62]	train-mlogloss:0.09694	eval-mlogloss:0.04547
[63]	train-mlogloss:0.09664	eval-mlogloss:0.04590
[64]	train-mlogloss:0.09644	eval-mlogloss:0.04619
[65]	train-mlogloss:0.09612	eval-mlogloss:0.04584
[66]	train-mlogloss:0.09566	eval-mlogloss:0.04448
[67]	train-mlogloss:0.09525	eval-mlogloss:0.04353
[68]	train-mlogloss:0.09530	eval-mlogloss:0.04317
[69]	train-mlogloss:0.09520	eval-mlogloss:0.04301
[70]	train-mlogloss:0.09486	eval-mlogloss:0.04367
[71]	train-mlogloss:0.09476	eval-mlogloss:0.04375
[72]	train-mlogloss:0.09392	eval-mlogloss:0.04189
[73]	train-mlogloss:0.09358	eval-mlogloss:0.04143
[74]	train-mlogloss:0.09343	eval-mlogloss:0.04162
[75]	train-mlogloss:0.09335	eval-mlogloss:0.04151
[76]	train-mlogloss:0.09326	eval-mlogloss:0.04134
[77]	train-mlogloss:0.09305	eval-mlogloss:0.04055
[78]	train-mlogloss:0.09260	eval-mlogloss:0.04059
[79]	train-mlogloss:0.09199	eval-mlogloss:0.03963
[80]	train-mlogloss:0.09200	eval-mlogloss:0.03941
[81]	train-mlogloss:0.09189	eval-mlogloss:0.03952
[82]	train-mlogloss:0.09144	eval-mlogloss:0.03988
[83]	train-mlogloss:0.09085	eval-mlogloss:0.03884
[84]	train-mlogloss:0.09072	eval-mlogloss:0.03909
[85]	train-mlogloss:0.09077	eval-mlogloss:0.03880
[86]	train-mlogloss:0.09078	eval-mlogloss:0.03920
[87]	train-mlogloss:0.09080	eval-mlogloss:0.03933
[88]	train-mlogloss:0.09065	eval-mlogloss:0.03828
[89]	train-mlogloss:0.09034	eval-mlogloss:0.03837
[90]	train-mlogloss:0.09006	eval-mlogloss:0.03796
[91]	train-mlogloss:0.09018	eval-mlogloss:0.03758
[92]	train-mlogloss:0.09003	eval-mlogloss:0.03791
[93]	train-mlogloss:0.09019	eval-mlogloss:0.03763
[94]	train-mlogloss:0.09002	eval-mlogloss:0.03783
[95]	train-mlogloss:0.09004	eval-mlogloss:0.03802
[96]	train-mlogloss:0.08967	eval-mlogloss:0.03745
[97]	train-mlogloss:0.08905	eval-mlogloss:0.03700
[98]	train-mlogloss:0.08866	eval-mlogloss:0.03721
[99]	train-mlogloss:0.08845	eval-mlogloss:0.03685
[100]	train-mlogloss:0.08784	eval-mlogloss:0.03674
[101]	train-mlogloss:0.08779	eval-mlogloss:0.03686
[102]	train-mlogloss:0.08768	eval-mlogloss:0.03715
[103]	train-mlogloss:0.08741	eval-mlogloss:0.03679
[104]	train-mlogloss:0.08700	eval-mlogloss:0.03628
[105]	train-mlogloss:0.08697	eval-mlogloss:0.03585
[106]	train-mlogloss:0.08691	eval-mlogloss:0.03504
[107]	train-mlogloss:0.08662	eval-mlogloss:0.03486
[108]	train-mlogloss:0.08661	eval-mlogloss:0.03486
[109]	train-mlogloss:0.08663	eval-mlogloss:0.03470
[110]	train-mlogloss:0.08656	eval-mlogloss:0.03500
[111]	train-mlogloss:0.08659	eval-mlogloss:0.03561
[112]	train-mlogloss:0.08638	eval-mlogloss:0.03608
[113]	train-mlogloss:0.08616	eval-mlogloss:0.03512
[114]	train-mlogloss:0.08584	eval-mlogloss:0.03479
[115]	train-mlogloss:0.08569	eval-mlogloss:0.03450
[116]	train-mlogloss:0.08564	eval-mlogloss:0.03457
[117]	train-mlogloss:0.08546	eval-mlogloss:0.03457
[118]	train-mlogloss:0.08562	eval-mlogloss:0.03515
[119]	train-mlogloss:0.08547	eval-mlogloss:0.03521
[120]	train-mlogloss:0.08580	eval-mlogloss:0.03557
[121]	train-mlogloss:0.08603	eval-mlogloss:0.03589
[122]	train-mlogloss:0.08583	eval-mlogloss:0.03572
[123]	train-mlogloss:0.08593	eval-mlogloss:0.03606
[124]	train-mlogloss:0.08570	eval-mlogloss:0.03569
[125]	train-mlogloss:0.08533	eval-mlogloss:0.03531
[126]	train-mlogloss:0.08513	eval-mlogloss:0.03506
[127]	train-mlogloss:0.08524	eval-mlogloss:0.03562
[128]	train-mlogloss:0.08520	eval-mlogloss:0.03619
[129]	train-mlogloss:0.08513	eval-mlogloss:0.03582
[130]	train-mlogloss:0.08485	eval-mlogloss:0.03612
[131]	train-mlogloss:0.08439	eval-mlogloss:0.03590
[132]	train-mlogloss:0.08428	eval-mlogloss:0.03537
[133]	train-mlogloss:0.08428	eval-mlogloss:0.03519
[134]	train-mlogloss:0.08418	eval-mlogloss:0.03495
[135]	train-mlogloss:0.08422	eval-mlogloss:0.03485
[136]	train-mlogloss:0.08395	eval-mlogloss:0.03579
[137]	train-mlogloss:0.08397	eval-mlogloss:0.03568
[138]	train-mlogloss:0.08396	eval-mlogloss:0.03591
[139]	train-mlogloss:0.08381	eval-mlogloss:0.03575
[140]	train-mlogloss:0.08370	eval-mlogloss:0.03498
[141]	train-mlogloss:0.08368	eval-mlogloss:0.03486
[142]	train-mlogloss:0.08356	eval-mlogloss:0.03502
[143]	train-mlogloss:0.08342	eval-mlogloss:0.03474
[144]	train-mlogloss:0.08327	eval-mlogloss:0.03500
[145]	train-mlogloss:0.08304	eval-mlogloss:0.03499

[I 2026-09-18 14:49:11,814] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.4615865539522488, 'alpha': 1.2134881023806185e-07, 'eta': 0.11086234924671506, 'gamma': 0.0007573046559592897, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.5405988373837154, 'colsample_bytree': 0.6903188324155567}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.82850	eval-mlogloss:0.80820
[1]	train-mlogloss:0.64940	eval-mlogloss:0.61196

[I 2026-09-18 14:49:11,834] Trial 2 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94115	eval-mlogloss:0.93217
[1]	train-mlogloss:0.77936	eval-mlogloss:0.76182

[I 2026-09-18 14:49:11,852] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91741	eval-mlogloss:0.90807
[1]	train-mlogloss:0.76956	eval-mlogloss:0.74937

[I 2026-09-18 14:49:11,866] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90788	eval-mlogloss:0.89450
[1]	train-mlogloss:0.71845	eval-mlogloss:0.69479

[I 2026-09-18 14:49:11,879] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.83747	eval-mlogloss:0.84021
[1]	train-mlogloss:0.63381	eval-mlogloss:0.62331

[I 2026-09-18 14:49:11,890] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87438	eval-mlogloss:0.86213
[1]	train-mlogloss:0.66990	eval-mlogloss:0.64732

[I 2026-09-18 14:49:11,901] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04660	eval-mlogloss:1.04212
[1]	train-mlogloss:0.98230	eval-mlogloss:0.97589
[2]	train-mlogloss:0.92183	eval-mlogloss:0.91058
[3]	train-mlogloss:0.87490	eval-mlogloss:0.86064
[4]	train-mlogloss:0.82375	eval-mlogloss:0.80701
[5]	train-mlogloss:0.78147	eval-mlogloss:0.76184
[6]	train-mlogloss:0.74382	eval-mlogloss:0.72320
[7]	train-mlogloss:0.71971	eval-mlogloss:0.69856
[8]	train-mlogloss:0.68721	eval-mlogloss:0.66395
[9]	train-mlogloss:0.65108	eval-mlogloss:0.62506
[10]	train-mlogloss:0.62620	eval-mlogloss:0.59757
[11]	train-mlogloss:0.59853	eval-mlogloss:0.56538
[12]	train-mlogloss:0.57474	eval-mlogloss:0.54179
[13]	train-mlogloss:0.55493	eval-mlogloss:0.52061
[14]	train-mlogloss:0.52926	eval-mlogloss:0.49350
[15]	train-mlogloss:0.50468	eval-mlogloss:0.46616
[16]	train-mlogloss:0.48418	eval-mlogloss:0.44235
[17]	train-mlogloss:0.46258	eval-mlogloss:0.41850
[18]	train-mlogloss:0.44794	eval-mlogloss:0.40322
[19]	train-mlogloss:0.43760	eval-mlogloss:0.39135
[20]	train-mlogloss:0.41996	eval-mlogloss:0.37155
[21]	train-mlogloss:0.40726	eval-mlogloss:0.35728
[22]	train-mlogloss:0.39537	eval-mlogloss:0.34307
[23]	train-mlogloss:0.38456	eval-mlogloss:0.33283
[24]	train-mlogloss:0.37548	eval-mlogloss:0.32248
[25]	train-mlogloss:0.36484	eval-mlogloss:0.31103
[26]	train-mlogloss:0.35507	eval-mlogloss:0.30071
[27]	train-mlogloss:0.34467	eval-mlogloss:0.28977
[28]	train-mlogloss:0.33622	eval-mlogloss:0.28007
[29]	train-mlogloss:0.33458	eval-mlogloss:0.27794
[30]	train-mlogloss:0.33334	eval-mlogloss:0.27585
[31]	train-mlogloss:0.32924	eval-mlogloss:0.27057
[32]	train-mlogloss:0.32479	eval-mlogloss:0.26572
[33]	train-mlogloss:0.32489	eval-mlogloss:0.26576
[34]	train-mlogloss:0.32474	eval-mlogloss:0.26554
[35]	train-mlogloss:0.31880	eval-mlogloss:0.25837
[36]	train-mlogloss:0.31867	eval-mlogloss:0.25856
[37]	train-mlogloss:0.31498	eval-mlogloss:0.25387
[38]	train-mlogloss:0.30696	eval-mlogloss:0.24491
[39]	train-mlogloss:0.30409	eval-mlogloss:0.24193
[40]	train-mlogloss:0.30142	eval-mlogloss:0.23830
[41]	train-mlogloss:0.30120	eval-mlogloss:0.23828
[42]	train-mlogloss:0.29694	eval-mlogloss:0.23434
[43]	train-mlogloss:0.29414	eval-mlogloss:0.23085
[44]	train-mlogloss:0.29406	eval-mlogloss:0.23075
[45]	train-mlogloss:0.29212	eval-mlogloss:0.22785
[46]	train-mlogloss:0.29205	eval-mlogloss:0.22779
[47]	train-mlogloss:0.28976	eval-mlogloss:0.22499
[48]	train-mlogloss:0.28949	eval-mlogloss:0.22413
[49]	train-mlogloss:0.28913	eval-mlogloss:0.22389
[50]	train-mlogloss:0.28899	eval-mlogloss:0.22375
[51]	train-mlogloss:0.28849	eval-mlogloss:0.22234
[52]	train-mlogloss:0.28632	eval-mlogloss:0.21973
[53]	train-mlogloss:0.28290	eval-mlogloss:0.21595
[54]	train-mlogloss:0.28294	eval-mlogloss:0.21590
[55]	train-mlogloss:0.28255	eval-mlogloss:0.21482
[56]	train-mlogloss:0.28245	eval-mlogloss:0.21471
[57]	train-mlogloss:0.28232	eval-mlogloss:0.21462
[58]	train-mlogloss:0.28211	eval-mlogloss:0.21437
[59]	train-mlogloss:0.27964	eval-mlogloss:0.21125
[60]	train-mlogloss:0.27944	eval-mlogloss:0.21121
[61]	train-mlogloss:0.27916	eval-mlogloss:0.21099
[62]	train-mlogloss:0.27896	eval-mlogloss:0.21079
[63]	train-mlogloss:0.27871	eval-mlogloss:0.21015
[64]	train-mlogloss:0.27856	eval-mlogloss:0.20968
[65]	train-mlogloss:0.27838	eval-mlogloss:0.20951
[66]	train-mlogloss:0.27830	eval-mlogloss:0.20961
[67]	train-mlogloss:0.27834	eval-mlogloss:0.20967
[68]	train-mlogloss:0.27835	eval-mlogloss:0.20974
[69]	train-mlogloss:0.27824	eval-mlogloss:0.20958
[70]	train-mlogloss:0.27808	eval-mlogloss:0.20950
[71]	train-mlogloss:0.27791	eval-mlogloss:0.20949
[72]	train-mlogloss:0.27767	eval-mlogloss:0.20879
[73]	train-mlogloss:0.27767	eval-mlogloss:0.20875
[74]	train-mlogloss:0.27765	eval-mlogloss:0.20883
[75]	train-mlogloss:0.27739	eval-mlogloss:0.20792
[76]	train-mlogloss:0.27715	eval-mlogloss:0.20763
[77]	train-mlogloss:0.27686	eval-mlogloss:0.20738
[78]	train-mlogloss:0.27663	eval-mlogloss:0.20713
[79]	train-mlogloss:0.27439	eval-mlogloss:0.20450
[80]	train-mlogloss:0.27418	eval-mlogloss:0.20390
[81]	train-mlogloss:0.27418	eval-mlogloss:0.20390
[82]	train-mlogloss:0.27397	eval-mlogloss:0.20373
[83]	train-mlogloss:0.27365	eval-mlogloss:0.20355
[84]	train-mlogloss:0.27363	eval-mlogloss:0.20357
[85]	train-mlogloss:0.27350	eval-mlogloss:0.20341
[86]	train-mlogloss:0.27337	eval-mlogloss:0.20303
[87]	train-mlogloss:0.27326	eval-mlogloss:0.20294
[88]	train-mlogloss:0.27283	eval-mlogloss:0.20252
[89]	train-mlogloss:0.27282	eval-mlogloss:0.20253
[90]	train-mlogloss:0.27252	eval-mlogloss:0.20150
[91]	train-mlogloss:0.27252	eval-mlogloss:0.20140
[92]	train-mlogloss:0.27246	eval-mlogloss:0.20152
[93]	train-mlogloss:0.27240	eval-mlogloss:0.20137
[94]	train-mlogloss:0.27238	eval-mlogloss:0.20145
[95]	train-mlogloss:0.27219	eval-mlogloss:0.20097
[96]	train-mlogloss:0.27218	eval-mlogloss:0.20107
[97]	train-mlogloss:0.27197	eval-mlogloss:0.20089
[98]	train-mlogloss:0.27180	eval-mlogloss:0.20080
[99]	train-mlogloss:0.27170	eval-mlogloss:0.20082
[100]	train-mlogloss:0.27162	eval-mlogloss:0.20076
[101]	train-mlogloss:0.27156	eval-mlogloss:0.20049
[102]	train-mlogloss:0.27139	eval-mlogloss:0.20033
[103]	train-mlogloss:0.27141	eval-mlogloss:0.20047
[104]	train-mlogloss:0.27129	eval-mlogloss:0.20041
[105]	train-mlogloss:0.27112	eval-mlogloss:0.20025
[106]	train-mlogloss:0.27094	eval-mlogloss:0.20015
[107]	train-mlogloss:0.27034	eval-mlogloss:0.19923
[108]	train-mlogloss:0.27028	eval-mlogloss:0.19913
[109]	train-mlogloss:0.27016	eval-mlogloss:0.19873
[110]	train-mlogloss:0.27016	eval-mlogloss:0.19878
[111]	train-mlogloss:0.27007	eval-mlogloss:0.19897
[112]	train-mlogloss:0.26974	eval-mlogloss:0.19874
[113]	train-mlogloss:0.26961	eval-mlogloss:0.19864
[114]	train-mlogloss:0.26952	eval-mlogloss:0.19859
[115]	train-mlogloss:0.26936	eval-mlogloss:0.19802
[116]	train-mlogloss:0.26930	eval-mlogloss:0.19803
[117]	train-mlogloss:0.26720	eval-mlogloss:0.19539
[118]	train-mlogloss:0.26726	eval-mlogloss:0.19537
[119]	train-mlogloss:0.26708	eval-mlogloss:0.19540
[120]	train-mlogloss:0.26694	eval-mlogloss:0.19548
[121]	train-mlogloss:0.26695	eval-mlogloss:0.19560
[122]	train-mlogloss:0.26467	eval-mlogloss:0.19300
[123]	train-mlogloss:0.26465	eval-mlogloss:0.19279
[124]	train-mlogloss:0.26465	eval-mlogloss:0.19270
[125]	train-mlogloss:0.26453	eval-mlogloss:0.19266
[126]	train-mlogloss:0.26441	eval-mlogloss:0.19236
[127]	train-mlogloss:0.26443	eval-mlogloss:0.19245
[128]	train-mlogloss:0.26440	eval-mlogloss:0.19241
[129]	train-mlogloss:0.26440	eval-mlogloss:0.19238
[130]	train-mlogloss:0.26427	eval-mlogloss:0.19190
[131]	train-mlogloss:0.26354	eval-mlogloss:0.19036
[132]	train-mlogloss:0.26344	eval-mlogloss:0.19021
[133]	train-mlogloss:0.26340	eval-mlogloss:0.19028
[134]	train-mlogloss:0.26317	eval-mlogloss:0.19020
[135]	train-mlogloss:0.26305	eval-mlogloss:0.19013
[136]	train-mlogloss:0.26296	eval-mlogloss:0.19014
[137]	train-mlogloss:0.26296	eval-mlogloss:0.19011
[138]	train-mlogloss:0.26297	eval-mlogloss:0.19005
[139]	train-mlogloss:0.26291	eval-mlogloss:0.19020
[140]	train-mlogloss:0.26294	eval-mlogloss:0.19003
[141]	train-mlogloss:0.26291	eval-mlogloss:0.18995
[142]	train-mlogloss:0.26288	eval-mlogloss:0.19010
[143]	train-mlogloss:0.26278	eval-mlogloss:0.18979
[144]	train-mlogloss:0.26278	eval-mlogloss:0.18978
[145]	train-mlogloss:0.26268	eval-mlogloss:0.18969
[146]	train-mlogloss:0.26257	eval-mlogloss:0.18973
[147]	train-mlogloss:0.26085	eval-mlogloss:0.18729
[148]	train-mlogloss:0.26084	eval-mlogloss:0.18742
[149]	train-mlogloss:0.26076	eval-mlogloss:0.18708
[150]	train-mlogloss:0.26065	eval-mlogloss:0.18710
[151]	train-mlogloss:0.26065	eval-mlogloss:0.18706
[152]	train-mlogloss:0.26054	eval-mlogloss:0.18694
[153]	train-mlogloss:0.26054	eval-mlogloss:0.18680
[154]	train-mlogloss:0.26054	eval-mlogloss:0.18674
[155]	train-mlogloss:0.26054	eval-mlogloss:0.18667
[156]	train-mlogloss:0.25902	eval-mlogloss:0.18482
[157]	train-mlogloss:0.25902	eval-mlogloss:0.18497
[158]	train-mlogloss:0.25902	eval-mlogloss:0.18507
[159]	train-mlogloss:0.25903	eval-mlogloss:0.18504
[160]	train-mlogloss:0.25888	eval-mlogloss:0.18489
[161]	train-mlogloss:0.25889	eval-mlogloss:0.18478
[162]	train-mlogloss:0.25887	eval-mlogloss:0.18485
[163]	train-mlogloss:0.25887	eval-mlogloss:0.18487
[164]	train-mlogloss:0.25887	eval-mlogloss:0.18489
[165]	train-mlogloss:0.25880	eval-mlogloss:0.18488
[166]	train-mlogloss:0.25880	eval-mlogloss:0.18477
[167]	train-mlogloss:0.25880	eval-mlogloss:0.18480
[168]	train-mlogloss:0.25881	eval-mlogloss:0.18474
[169]	train-mlogloss:0.25864	eval-mlogloss:0.18399
[170]	train-mlogloss:0.25856	eval-mlogloss:0.18401
[171]	train-mlogloss:0.25853	eval-mlogloss:0.18394
[172]	train-mlogloss:0.25847	eval-mlogloss:0.18358
[173]	train-mlogloss:0.25847	eval-mlogloss:0.18356
[174]	train-mlogloss:0.25830	eval-mlogloss:0.18357
[175]	train-mlogloss:0.25830	eval-mlogloss:0.18351
[176]	train-mlogloss:0.25828	eval-mlogloss:0.18353
[177]	train-mlogloss:0.25822	eval-mlogloss:0.18334
[178]	train-mlogloss:0.25820	eval-mlogloss:0.18319
[179]	train-mlogloss:0.25808	eval-mlogloss:0.18309
[180]	train-mlogloss:0.25808	eval-mlogloss:0.18306
[181]	train-mlogloss:0.25810	eval-mlogloss:0.18294
[182]	train-mlogloss:0.25805	eval-mlogloss:0.18235
[183]	train-mlogloss:0.25803	eval-mlogloss:0.18241
[184]	train-mlogloss:0.25796	eval-mlogloss:0.18242
[185]	train-mlogloss:0.25798	eval-mlogloss:0.18234
[186]	train-mlogloss:0.25796	eval-mlogloss:0.18250
[187]	train-mlogloss:0.25795	eval-mlogloss:0.18255
[188]	train-mlogloss:0.25796	eval-mlogloss:0.18241
[189]	train-mlogloss:0.25782	eval-mlogloss:0.18168
[190]	train-mlogloss:0.25785	eval-mlogloss:0.18158
[191]	train-mlogloss:0.25782	eval-mlogloss:0.18161
[192]	train-mlogloss:0.25782	eval-mlogloss:0.18159
[193]	train-mlogloss:0.25781	eval-mlogloss:0.18164
[194]	train-mlogloss:0.25772	eval-mlogloss:0.18139
[195]	train-mlogloss:0.25769	eval-mlogloss:0.18135
[196]	train-mlogloss:0.25769	eval-mlogloss:0.18134
[197]	train-mlogloss:0.25768	eval-mlogloss:0.18137
[198]	train-mlogloss:0.25765	eval-mlogloss:0.18139
[199]	train-mlogloss:0.25762	eval-mlogloss:0.18150
[200]	train-mlogloss:0.25763	eval-mlogloss:0.18150
[201]	train-mlogloss:0.25763	eval-mlogloss:0.18149
[202]	train-mlogloss:0.25761	eval-mlogloss:0.18152
[203]	train-mlogloss:0.25755	eval-mlogloss:0.18167
[204]	train-mlogloss:0.25744	eval-mlogloss:0.18158
[205]	train-mlogloss:0.25744	eval-mlogloss:0.18162
[206]	train-mlogloss:0.25734	eval-mlogloss:0.18158
[207]	train-mlogloss:0.25730	eval-mlogloss:0.18154
[208]	train-mlogloss:0.25731	eval-mlogloss:0.18162
[209]	train-mlogloss:0.25730	eval-mlogloss:0.18159
[210]	train-mlogloss:0.25731	eval-mlogloss:0.18166
[211]	train-mlogloss:0.25729	eval-mlogloss:0.18170
[212]	train-mlogloss:0.25724	eval-mlogloss:0.18180
[213]	train-mlogloss:0.25717	eval-mlogloss:0.18192
[214]	train-mlogloss:0.25719	eval-mlogloss:0.18198
[215]	train-mlogloss:0.25717	eval-mlogloss:0.18188
[216]	train-mlogloss:0.25717	eval-mlogloss:0.18188
[217]	train-mlogloss:0.25712	eval-mlogloss:0.18168
[218]	train-mlogloss:0.25712	eval-mlogloss:0.18176
[219]	train-mlogloss:0.25710	eval-mlogloss:0.18173
[220]	train-mlogloss:0.25710	eval-mlogloss:0.18167
[221]	train-mlogloss:0.25711	eval-mlogloss:0.18171
[222]	train-mlogloss:0.25709	eval-mlogloss:0.18173
[223]	train-mlogloss:0.25655	eval-mlogloss:0.18098
[224]	train-mlogloss:0.25654	eval-mlogloss:0.18104
[225]	train-mlogloss:0.25652	eval-mlogloss:0.18098
[226]	train-mlogloss:0.25654	eval-mlogloss:0.18100
[227]	train-mlogloss:0.25647	eval-mlogloss:0.18083
[228]	train-mlogloss:0.25637	eval-mlogloss:0.18090
[229]	train-mlogloss:0.25639	eval-mlogloss:0.18090
[230]	train-mlogloss:0.25638	eval-mlogloss:0.18077
[231]	train-mlogloss:0.25636	eval-mlogloss:0.18072
[232]	train-mlogloss:0.25637	eval-mlogloss:0.18080
[233]	train-mlogloss:0.25626	eval-mlogloss:0.18052
[234]	train-mlogloss:0.25627	eval-mlogloss:0.18058
[235]	train-mlogloss:0.25625	eval-mlogloss:0.18057
[236]	train-mlogloss:0.25624	eval-mlogloss:0.18049
[237]	train-mlogloss:0.25624	eval-mlogloss:0.18053
[238]	train-mlogloss:0.25618	eval-mlogloss:0.18052
[239]	train-mlogloss:0.25619	eval-mlogloss:0.18040
[240]	train-mlogloss:0.25620	eval-mlogloss:0.18032
[241]	train-mlogloss:0.25614	eval-mlogloss:0.18021
[242]	train-mlogloss:0.25609	eval-mlogloss:0.18024
[243]	train-mlogloss:0.25607	eval-mlogloss:0.18008
[244]	train-mlogloss:0.25606	eval-mlogloss:0.18013
[245]	train-mlogloss:0.25604	eval-mlogloss:0.18020
[246]	train-mlogloss:0.25603	eval-mlogloss:0.18031
[247]	train-mlogloss:0.25602	eval-mlogloss:0.18034
[248]	train-mlogloss:0.25604	eval-mlogloss:0.18025
[249]	train-mlogloss:0.25600	eval-mlogloss:0.18015
[250]	train-mlogloss:0.25600	eval-mlogloss:0.18018
[251]	train-mlogloss:0.25600	eval-mlogloss:0.18020
[252]	train-mlogloss:0.25593	eval-mlogloss:0.17961
[253]	train-mlogloss:0.25594	eval-mlogloss:0.17955
[254]	train-mlogloss:0.25583	eval-mlogloss:0.17957
[255]	train-mlogloss:0.25583	eval-mlogloss:0.17950
[256]	train-mlogloss:0.25582	eval-mlogloss:0.17956
[257]	train-mlogloss:0.25582	eval-mlogloss:0.17956
[258]	train-mlogloss:0.25581	eval-mlogloss:0.17961
[259]	train-mlogloss:0.25581	eval-mlogloss:0.17971
[260]	train-mlogloss:0.25582	eval-mlogloss:0.17975
[261]	train-mlogloss:0.25580	eval-mlogloss:0.17976
[262]	train-mlogloss:0.25581	eval-mlogloss:0.17980
[263]	train-mlogloss:0.25578	eval-mlogloss:0.17983
[264]	train-mlogloss:0.25575	eval-mlogloss:0.17993
[265]	train-mlogloss:0.25573	eval-mlogloss:0.18000
[266]	train-mlogloss:0.25574	eval-mlogloss:0.17994
[267]	train-mlogloss:0.25567	eval-mlogloss:0.17988
[268]	train-mlogloss:0.25568	eval-mlogloss:0.17980
[269]	train-mlogloss:0.25568	eval-mlogloss:0.17984
[270]	train-mlogloss:0.25560	eval-mlogloss:0.18001
[271]	train-mlogloss:0.25558	eval-mlogloss:0.18017
[272]	train-mlogloss:0.25558	eval-mlogloss:0.18014
[273]	train-mlogloss:0.25555	eval-mlogloss:0.18023
[274]	train-mlogloss:0.25555	eval-mlogloss:0.18023
[275]	train-mlogloss:0.25555	eval-mlogloss:0.18020
[276]	train-mlogloss:0.25555	eval-mlogloss:0.18016
[277]	train-mlogloss:0.25555	eval-mlogloss:0.18017
[278]	train-mlogloss:0.25555	eval-mlogloss:0.18016
[279]	train-mlogloss:0.25555	eval-mlogloss:0.18020
[280]	train-mlogloss:0.25555	eval-mlogloss:0.18026
[281]	train-mlogloss:0.25544	eval-mlogloss:0.18018
[282]	train-mlogloss:0.25546	eval-mlogloss:0.18001
[283]	train-mlogloss:0.25527	eval-mlogloss:0.17997
[284]	train-mlogloss:0.25526	eval-mlogloss:0.18002
[285]	train-mlogloss:0.25526	eval-mlogloss:0.18009

[I 2026-09-18 14:49:12,852] Trial 8 finished with value: 1.0 and parameters: {'lambda': 2.3151654901211934e-08, 'alpha': 0.0030024604462847593, 'eta': 0.055634239346742734, 'gamma': 0.013264790944592595, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.6434818229740068, 'colsample_bytree': 0.6102005550833914}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.96658	eval-mlogloss:0.97018
[1]	train-mlogloss:0.83488	eval-mlogloss:0.83162

[I 2026-09-18 14:49:12,869] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86260	eval-mlogloss:0.86303
[1]	train-mlogloss:0.68354	eval-mlogloss:0.67142

[I 2026-09-18 14:49:12,895] Trial 10 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96770	eval-mlogloss:0.96756
[1]	train-mlogloss:0.82163	eval-mlogloss:0.81218

[I 2026-09-18 14:49:12,911] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03249	eval-mlogloss:1.03197
[1]	train-mlogloss:0.96046	eval-mlogloss:0.95750
[2]	train-mlogloss:0.89659	eval-mlogloss:0.89018
[3]	train-mlogloss:0.84269	eval-mlogloss:0.83667
[4]	train-mlogloss:0.78999	eval-mlogloss:0.78144
[5]	train-mlogloss:0.74325	eval-mlogloss:0.73185
[6]	train-mlogloss:0.70035	eval-mlogloss:0.69058
[7]	train-mlogloss:0.66852	eval-mlogloss:0.65675

[I 2026-09-18 14:49:12,948] Trial 12 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.00129	eval-mlogloss:0.99487
[1]	train-mlogloss:0.91723	eval-mlogloss:0.90630
[2]	train-mlogloss:0.84236	eval-mlogloss:0.82524
[3]	train-mlogloss:0.77707	eval-mlogloss:0.75876
[4]	train-mlogloss:0.71584	eval-mlogloss:0.69488
[5]	train-mlogloss:0.66286	eval-mlogloss:0.64057
[6]	train-mlogloss:0.61550	eval-mlogloss:0.59013
[7]	train-mlogloss:0.57297	eval-mlogloss:0.54708

[I 2026-09-18 14:49:12,998] Trial 13 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.90135	eval-mlogloss:0.89104
[1]	train-mlogloss:0.74695	eval-mlogloss:0.72507

[I 2026-09-18 14:49:13,021] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97225	eval-mlogloss:0.96182
[1]	train-mlogloss:0.84010	eval-mlogloss:0.82307

[I 2026-09-18 14:49:13,054] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08013	eval-mlogloss:1.08199
[1]	train-mlogloss:1.06093	eval-mlogloss:1.06160
[2]	train-mlogloss:1.04279	eval-mlogloss:1.04263
[3]	train-mlogloss:1.02547	eval-mlogloss:1.02371
[4]	train-mlogloss:1.00786	eval-mlogloss:1.00514
[5]	train-mlogloss:0.99129	eval-mlogloss:0.98807
[6]	train-mlogloss:0.97511	eval-mlogloss:0.97109
[7]	train-mlogloss:0.95903	eval-mlogloss:0.95416
[8]	train-mlogloss:0.94322	eval-mlogloss:0.93737
[9]	train-mlogloss:0.92800	eval-mlogloss:0.92135
[10]	train-mlogloss:0.91298	eval-mlogloss:0.90609
[11]	train-mlogloss:0.89897	eval-mlogloss:0.89124
[12]	train-mlogloss:0.88520	eval-mlogloss:0.87723
[13]	train-mlogloss:0.87095	eval-mlogloss:0.86263
[14]	train-mlogloss:0.85708	eval-mlogloss:0.84786
[15]	train-mlogloss:0.84349	eval-mlogloss:0.83345
[16]	train-mlogloss:0.83068	eval-mlogloss:0.81945
[17]	train-mlogloss:0.81826	eval-mlogloss:0.80599
[18]	train-mlogloss:0.80540	eval-mlogloss:0.79340
[19]	train-mlogloss:0.79322	eval-mlogloss:0.78052
[20]	train-mlogloss:0.78080	eval-mlogloss:0.76717
[21]	train-mlogloss:0.76897	eval-mlogloss:0.75474
[22]	train-mlogloss:0.75859	eval-mlogloss:0.74445
[23]	train-mlogloss:0.74742	eval-mlogloss:0.73382
[24]	train-mlogloss:0.73640	eval-mlogloss:0.72173
[25]	train-mlogloss:0.72552	eval-mlogloss:0.71046
[26]	train-mlogloss:0.71485	eval-mlogloss:0.69854
[27]	train-mlogloss:0.70399	eval-mlogloss:0.68707
[28]	train-mlogloss:0.69385	eval-mlogloss:0.67654
[29]	train-mlogloss:0.68365	eval-mlogloss:0.66552
[30]	train-mlogloss:0.67411	eval-mlogloss:0.65555
[31]	train-mlogloss:0.66442	eval-mlogloss:0.64525
[32]	train-mlogloss:0.65487	eval-mlogloss:0.63514
[33]	train-mlogloss:0.64566	eval-mlogloss:0.62538
[34]	train-mlogloss:0.63642	eval-mlogloss:0.61578
[35]	train-mlogloss:0.62745	eval-mlogloss:0.60600
[36]	train-mlogloss:0.61920	eval-mlogloss:0.59728
[37]	train-mlogloss:0.61060	eval-mlogloss:0.58814
[38]	train-mlogloss:0.60139	eval-mlogloss:0.57893
[39]	train-mlogloss:0.59286	eval-mlogloss:0.57029
[40]	train-mlogloss:0.58460	eval-mlogloss:0.56230
[41]	train-mlogloss:0.57677	eval-mlogloss:0.55403
[42]	train-mlogloss:0.56884	eval-mlogloss:0.54602
[43]	train-mlogloss:0.56128	eval-mlogloss:0.53784
[44]	train-mlogloss:0.55335	eval-mlogloss:0.53036
[45]	train-mlogloss:0.54563	eval-mlogloss:0.52223
[46]	train-mlogloss:0.53817	eval-mlogloss:0.51403
[47]	train-mlogloss:0.53078	eval-mlogloss:0.50662
[48]	train-mlogloss:0.52359	eval-mlogloss:0.49919
[49]	train-mlogloss:0.51673	eval-mlogloss:0.49216
[50]	train-mlogloss:0.51003	eval-mlogloss:0.48495
[51]	train-mlogloss:0.50320	eval-mlogloss:0.47750
[52]	train-mlogloss:0.49655	eval-mlogloss:0.47017
[53]	train-mlogloss:0.49006	eval-mlogloss:0.46324
[54]	train-mlogloss:0.48349	eval-mlogloss:0.45618
[55]	train-mlogloss:0.47687	eval-mlogloss:0.44879
[56]	train-mlogloss:0.47060	eval-mlogloss:0.44188
[57]	train-mlogloss:0.46442	eval-mlogloss:0.43549
[58]	train-mlogloss:0.45838	eval-mlogloss:0.42910
[59]	train-mlogloss:0.45269	eval-mlogloss:0.42293
[60]	train-mlogloss:0.44697	eval-mlogloss:0.41682
[61]	train-mlogloss:0.44107	eval-mlogloss:0.41061
[62]	train-mlogloss:0.43562	eval-mlogloss:0.40465
[63]	train-mlogloss:0.43021	eval-mlogloss:0.39883
[64]	train-mlogloss:0.42448	eval-mlogloss:0.39371
[65]	train-mlogloss:0.41925	eval-mlogloss:0.38809
[66]	train-mlogloss:0.41430	eval-mlogloss:0.38269
[67]	train-mlogloss:0.40890	eval-mlogloss:0.37671
[68]	train-mlogloss:0.40364	eval-mlogloss:0.37110
[69]	train-mlogloss:0.39826	eval-mlogloss:0.36659
[70]	train-mlogloss:0.39321	eval-mlogloss:0.36223
[71]	train-mlogloss:0.38839	eval-mlogloss:0.35698
[72]	train-mlogloss:0.38350	eval-mlogloss:0.35192
[73]	train-mlogloss:0.37904	eval-mlogloss:0.34697
[74]	train-mlogloss:0.37438	eval-mlogloss:0.34190
[75]	train-mlogloss:0.36992	eval-mlogloss:0.33736
[76]	train-mlogloss:0.36542	eval-mlogloss:0.33243
[77]	train-mlogloss:0.36119	eval-mlogloss:0.32768
[78]	train-mlogloss:0.35678	eval-mlogloss:0.32286
[79]	train-mlogloss:0.35238	eval-mlogloss:0.31832
[80]	train-mlogloss:0.34835	eval-mlogloss:0.31395
[81]	train-mlogloss:0.34406	eval-mlogloss:0.30956
[82]	train-mlogloss:0.34002	eval-mlogloss:0.30509
[83]	train-mlogloss:0.33612	eval-mlogloss:0.30149
[84]	train-mlogloss:0.33204	eval-mlogloss:0.29741
[85]	train-mlogloss:0.32825	eval-mlogloss:0.29377
[86]	train-mlogloss:0.32462	eval-mlogloss:0.28996
[87]	train-mlogloss:0.32096	eval-mlogloss:0.28667
[88]	train-mlogloss:0.31731	eval-mlogloss:0.28289
[89]	train-mlogloss:0.31357	eval-mlogloss:0.27946
[90]	train-mlogloss:0.30998	eval-mlogloss:0.27555
[91]	train-mlogloss:0.30631	eval-mlogloss:0.27211
[92]	train-mlogloss:0.30308	eval-mlogloss:0.26878
[93]	train-mlogloss:0.29952	eval-mlogloss:0.26505
[94]	train-mlogloss:0.29617	eval-mlogloss:0.26187
[95]	train-mlogloss:0.29288	eval-mlogloss:0.25825
[96]	train-mlogloss:0.28947	eval-mlogloss:0.25449
[97]	train-mlogloss:0.28635	eval-mlogloss:0.25145
[98]	train-mlogloss:0.28336	eval-mlogloss:0.24811
[99]	train-mlogloss:0.28035	eval-mlogloss:0.24528
[100]	train-mlogloss:0.27712	eval-mlogloss:0.24166
[101]	train-mlogloss:0.27404	eval-mlogloss:0.23877
[102]	train-mlogloss:0.27083	eval-mlogloss:0.23555
[103]	train-mlogloss:0.26777	eval-mlogloss:0.23216
[104]	train-mlogloss:0.26473	eval-mlogloss:0.22921
[105]	train-mlogloss:0.26179	eval-mlogloss:0.22597
[106]	train-mlogloss:0.25903	eval-mlogloss:0.22307
[107]	train-mlogloss:0.25635	eval-mlogloss:0.22023
[108]	train-mlogloss:0.25371	eval-mlogloss:0.21726
[109]	train-mlogloss:0.25103	eval-mlogloss:0.21430
[110]	train-mlogloss:0.24832	eval-mlogloss:0.21120
[111]	train-mlogloss:0.24556	eval-mlogloss:0.20821
[112]	train-mlogloss:0.24276	eval-mlogloss:0.20535
[113]	train-mlogloss:0.24029	eval-mlogloss:0.20228
[114]	train-mlogloss:0.23774	eval-mlogloss:0.20022
[115]	train-mlogloss:0.23513	eval-mlogloss:0.19771
[116]	train-mlogloss:0.23257	eval-mlogloss:0.19529
[117]	train-mlogloss:0.23009	eval-mlogloss:0.19284
[118]	train-mlogloss:0.22756	eval-mlogloss:0.19102
[119]	train-mlogloss:0.22536	eval-mlogloss:0.18881
[120]	train-mlogloss:0.22303	eval-mlogloss:0.18620
[121]	train-mlogloss:0.22082	eval-mlogloss:0.18394
[122]	train-mlogloss:0.21852	eval-mlogloss:0.18167
[123]	train-mlogloss:0.21641	eval-mlogloss:0.17943
[124]	train-mlogloss:0.21411	eval-mlogloss:0.17698
[125]	train-mlogloss:0.21186	eval-mlogloss:0.17520
[126]	train-mlogloss:0.20971	eval-mlogloss:0.17310
[127]	train-mlogloss:0.20712	eval-mlogloss:0.17135

[I 2026-09-18 14:49:13,489] Trial 16 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.04847	eval-mlogloss:1.04715
[1]	train-mlogloss:0.99857	eval-mlogloss:0.99442
[2]	train-mlogloss:0.95503	eval-mlogloss:0.94755
[3]	train-mlogloss:0.91388	eval-mlogloss:0.90228
[4]	train-mlogloss:0.87306	eval-mlogloss:0.85924
[5]	train-mlogloss:0.83640	eval-mlogloss:0.82183
[6]	train-mlogloss:0.80193	eval-mlogloss:0.78522
[7]	train-mlogloss:0.77018	eval-mlogloss:0.75159

[I 2026-09-18 14:49:13,537] Trial 17 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.97693	eval-mlogloss:0.97977
[1]	train-mlogloss:0.84832	eval-mlogloss:0.84284

[I 2026-09-18 14:49:13,600] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98827	eval-mlogloss:0.99678
[1]	train-mlogloss:0.86683	eval-mlogloss:0.86691

[I 2026-09-18 14:49:13,624] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00007	eval-mlogloss:0.99672
[1]	train-mlogloss:0.89383	eval-mlogloss:0.88631

[I 2026-09-18 14:49:13,640] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00829	eval-mlogloss:1.00069
[1]	train-mlogloss:0.90481	eval-mlogloss:0.89418

[I 2026-09-18 14:49:13,657] Trial 21 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93868	eval-mlogloss:0.94610
[1]	train-mlogloss:0.78955	eval-mlogloss:0.79190

[I 2026-09-18 14:49:13,686] Trial 22 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97401	eval-mlogloss:0.96694
[1]	train-mlogloss:0.86555	eval-mlogloss:0.85016

[I 2026-09-18 14:49:13,712] Trial 23 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96525	eval-mlogloss:0.95737
[1]	train-mlogloss:0.82561	eval-mlogloss:0.80845

[I 2026-09-18 14:49:13,729] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93892	eval-mlogloss:0.93133
[1]	train-mlogloss:0.80325	eval-mlogloss:0.78648

[I 2026-09-18 14:49:13,746] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94002	eval-mlogloss:0.92918
[1]	train-mlogloss:0.81059	eval-mlogloss:0.78917

[I 2026-09-18 14:49:13,768] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01714	eval-mlogloss:1.01403
[1]	train-mlogloss:0.92248	eval-mlogloss:0.91514
[2]	train-mlogloss:0.84441	eval-mlogloss:0.83290
[3]	train-mlogloss:0.78481	eval-mlogloss:0.76922
[4]	train-mlogloss:0.72090	eval-mlogloss:0.70200
[5]	train-mlogloss:0.66955	eval-mlogloss:0.64668
[6]	train-mlogloss:0.62244	eval-mlogloss:0.59516
[7]	train-mlogloss:0.59412	eval-mlogloss:0.56666

[I 2026-09-18 14:49:13,803] Trial 27 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.98459	eval-mlogloss:0.97781
[1]	train-mlogloss:0.88584	eval-mlogloss:0.87146

[I 2026-09-18 14:49:13,818] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01131	eval-mlogloss:1.00634
[1]	train-mlogloss:0.90985	eval-mlogloss:0.89918
[2]	train-mlogloss:0.82279	eval-mlogloss:0.80660
[3]	train-mlogloss:0.75710	eval-mlogloss:0.73563
[4]	train-mlogloss:0.68995	eval-mlogloss:0.66477
[5]	train-mlogloss:0.63595	eval-mlogloss:0.60641
[6]	train-mlogloss:0.59006	eval-mlogloss:0.55926
[7]	train-mlogloss:0.56139	eval-mlogloss:0.52975

[I 2026-09-18 14:49:13,861] Trial 29 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06151	eval-mlogloss:1.06116
[1]	train-mlogloss:1.01683	eval-mlogloss:1.01392
[2]	train-mlogloss:0.97541	eval-mlogloss:0.97048
[3]	train-mlogloss:0.93988	eval-mlogloss:0.93377
[4]	train-mlogloss:0.90280	eval-mlogloss:0.89471
[5]	train-mlogloss:0.87061	eval-mlogloss:0.86136
[6]	train-mlogloss:0.84106	eval-mlogloss:0.83119
[7]	train-mlogloss:0.81796	eval-mlogloss:0.80772
[8]	train-mlogloss:0.78914	eval-mlogloss:0.77653
[9]	train-mlogloss:0.76076	eval-mlogloss:0.74668
[10]	train-mlogloss:0.73333	eval-mlogloss:0.71712
[11]	train-mlogloss:0.70796	eval-mlogloss:0.68975
[12]	train-mlogloss:0.68708	eval-mlogloss:0.66839
[13]	train-mlogloss:0.66733	eval-mlogloss:0.64866
[14]	train-mlogloss:0.64381	eval-mlogloss:0.62396
[15]	train-mlogloss:0.62209	eval-mlogloss:0.60008
[16]	train-mlogloss:0.60127	eval-mlogloss:0.57658
[17]	train-mlogloss:0.58124	eval-mlogloss:0.55533
[18]	train-mlogloss:0.56187	eval-mlogloss:0.53482
[19]	train-mlogloss:0.54585	eval-mlogloss:0.51957
[20]	train-mlogloss:0.52799	eval-mlogloss:0.50155
[21]	train-mlogloss:0.51137	eval-mlogloss:0.48337
[22]	train-mlogloss:0.49904	eval-mlogloss:0.46986
[23]	train-mlogloss:0.48342	eval-mlogloss:0.45387
[24]	train-mlogloss:0.46890	eval-mlogloss:0.43793
[25]	train-mlogloss:0.45419	eval-mlogloss:0.42258
[26]	train-mlogloss:0.43994	eval-mlogloss:0.40630
[27]	train-mlogloss:0.42618	eval-mlogloss:0.39194
[28]	train-mlogloss:0.41397	eval-mlogloss:0.37884
[29]	train-mlogloss:0.40134	eval-mlogloss:0.36518
[30]	train-mlogloss:0.39279	eval-mlogloss:0.35780
[31]	train-mlogloss:0.38153	eval-mlogloss:0.34590

[I 2026-09-18 14:49:13,989] Trial 30 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.04852	eval-mlogloss:1.04955
[1]	train-mlogloss:0.99968	eval-mlogloss:0.99730
[2]	train-mlogloss:0.95459	eval-mlogloss:0.94962
[3]	train-mlogloss:0.91210	eval-mlogloss:0.90471
[4]	train-mlogloss:0.87312	eval-mlogloss:0.86323
[5]	train-mlogloss:0.83629	eval-mlogloss:0.82525
[6]	train-mlogloss:0.80301	eval-mlogloss:0.79090
[7]	train-mlogloss:0.77037	eval-mlogloss:0.75641

[I 2026-09-18 14:49:14,039] Trial 31 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04126	eval-mlogloss:1.04672
[1]	train-mlogloss:0.97439	eval-mlogloss:0.97612
[2]	train-mlogloss:0.91646	eval-mlogloss:0.91609
[3]	train-mlogloss:0.86516	eval-mlogloss:0.86089
[4]	train-mlogloss:0.81548	eval-mlogloss:0.81000
[5]	train-mlogloss:0.77081	eval-mlogloss:0.76298
[6]	train-mlogloss:0.73007	eval-mlogloss:0.72059
[7]	train-mlogloss:0.70063	eval-mlogloss:0.68957

[I 2026-09-18 14:49:14,073] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03970	eval-mlogloss:1.04390
[1]	train-mlogloss:0.97279	eval-mlogloss:0.97273
[2]	train-mlogloss:0.91249	eval-mlogloss:0.90807
[3]	train-mlogloss:0.86232	eval-mlogloss:0.85474
[4]	train-mlogloss:0.80922	eval-mlogloss:0.79891
[5]	train-mlogloss:0.76499	eval-mlogloss:0.75326
[6]	train-mlogloss:0.72554	eval-mlogloss:0.71002
[7]	train-mlogloss:0.69699	eval-mlogloss:0.68243

[I 2026-09-18 14:49:14,128] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07735	eval-mlogloss:1.07919
[1]	train-mlogloss:1.05545	eval-mlogloss:1.05580
[2]	train-mlogloss:1.03470	eval-mlogloss:1.03410
[3]	train-mlogloss:1.01497	eval-mlogloss:1.01253
[4]	train-mlogloss:0.99498	eval-mlogloss:0.99145
[5]	train-mlogloss:0.97623	eval-mlogloss:0.97213
[6]	train-mlogloss:0.95798	eval-mlogloss:0.95296
[7]	train-mlogloss:0.93992	eval-mlogloss:0.93396
[8]	train-mlogloss:0.92222	eval-mlogloss:0.91516
[9]	train-mlogloss:0.90523	eval-mlogloss:0.89729
[10]	train-mlogloss:0.88849	eval-mlogloss:0.88027
[11]	train-mlogloss:0.87284	eval-mlogloss:0.86377
[12]	train-mlogloss:0.85762	eval-mlogloss:0.84829
[13]	train-mlogloss:0.84189	eval-mlogloss:0.83220
[14]	train-mlogloss:0.82667	eval-mlogloss:0.81597
[15]	train-mlogloss:0.81179	eval-mlogloss:0.80019
[16]	train-mlogloss:0.79780	eval-mlogloss:0.78487
[17]	train-mlogloss:0.78425	eval-mlogloss:0.77018
[18]	train-mlogloss:0.76976	eval-mlogloss:0.75556
[19]	train-mlogloss:0.75657	eval-mlogloss:0.74157
[20]	train-mlogloss:0.74323	eval-mlogloss:0.72704
[21]	train-mlogloss:0.73056	eval-mlogloss:0.71372
[22]	train-mlogloss:0.71864	eval-mlogloss:0.70084
[23]	train-mlogloss:0.70665	eval-mlogloss:0.68948
[24]	train-mlogloss:0.69486	eval-mlogloss:0.67654
[25]	train-mlogloss:0.68325	eval-mlogloss:0.66452
[26]	train-mlogloss:0.67188	eval-mlogloss:0.65179
[27]	train-mlogloss:0.66020	eval-mlogloss:0.63970
[28]	train-mlogloss:0.64947	eval-mlogloss:0.62858
[29]	train-mlogloss:0.63878	eval-mlogloss:0.61709
[30]	train-mlogloss:0.62870	eval-mlogloss:0.60665
[31]	train-mlogloss:0.61817	eval-mlogloss:0.59594

[I 2026-09-18 14:49:14,258] Trial 34 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.01925	eval-mlogloss:1.01527
[1]	train-mlogloss:0.93075	eval-mlogloss:0.92169

[I 2026-09-18 14:49:14,287] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03066	eval-mlogloss:1.03276
[1]	train-mlogloss:0.95425	eval-mlogloss:0.95074

[I 2026-09-18 14:49:14,321] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06183	eval-mlogloss:1.06035
[1]	train-mlogloss:1.02708	eval-mlogloss:1.02313
[2]	train-mlogloss:0.99378	eval-mlogloss:0.98727
[3]	train-mlogloss:0.96228	eval-mlogloss:0.95411
[4]	train-mlogloss:0.93139	eval-mlogloss:0.92154
[5]	train-mlogloss:0.90205	eval-mlogloss:0.89123
[6]	train-mlogloss:0.87483	eval-mlogloss:0.86240
[7]	train-mlogloss:0.84879	eval-mlogloss:0.83572
[8]	train-mlogloss:0.82289	eval-mlogloss:0.80853
[9]	train-mlogloss:0.79813	eval-mlogloss:0.78260
[10]	train-mlogloss:0.77422	eval-mlogloss:0.75705
[11]	train-mlogloss:0.75145	eval-mlogloss:0.73452
[12]	train-mlogloss:0.73028	eval-mlogloss:0.71279
[13]	train-mlogloss:0.70952	eval-mlogloss:0.69118
[14]	train-mlogloss:0.68934	eval-mlogloss:0.66990
[15]	train-mlogloss:0.66932	eval-mlogloss:0.64830
[16]	train-mlogloss:0.65063	eval-mlogloss:0.62785
[17]	train-mlogloss:0.63265	eval-mlogloss:0.60906
[18]	train-mlogloss:0.61503	eval-mlogloss:0.59054
[19]	train-mlogloss:0.59835	eval-mlogloss:0.57263
[20]	train-mlogloss:0.58196	eval-mlogloss:0.55488
[21]	train-mlogloss:0.56615	eval-mlogloss:0.53852
[22]	train-mlogloss:0.55185	eval-mlogloss:0.52307
[23]	train-mlogloss:0.53700	eval-mlogloss:0.50786
[24]	train-mlogloss:0.52303	eval-mlogloss:0.49335
[25]	train-mlogloss:0.50918	eval-mlogloss:0.47935
[26]	train-mlogloss:0.49626	eval-mlogloss:0.46543
[27]	train-mlogloss:0.48292	eval-mlogloss:0.45263
[28]	train-mlogloss:0.47119	eval-mlogloss:0.44000
[29]	train-mlogloss:0.45917	eval-mlogloss:0.42843
[30]	train-mlogloss:0.44781	eval-mlogloss:0.41650
[31]	train-mlogloss:0.43689	eval-mlogloss:0.40473

[I 2026-09-18 14:49:14,443] Trial 37 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.06402	eval-mlogloss:1.06410
[1]	train-mlogloss:1.02927	eval-mlogloss:1.02697
[2]	train-mlogloss:0.99728	eval-mlogloss:0.99334
[3]	train-mlogloss:0.96606	eval-mlogloss:0.96046
[4]	train-mlogloss:0.93657	eval-mlogloss:0.92934
[5]	train-mlogloss:0.90886	eval-mlogloss:0.90108
[6]	train-mlogloss:0.88292	eval-mlogloss:0.87449
[7]	train-mlogloss:0.85720	eval-mlogloss:0.84680
[8]	train-mlogloss:0.83185	eval-mlogloss:0.81970
[9]	train-mlogloss:0.80770	eval-mlogloss:0.79415
[10]	train-mlogloss:0.78428	eval-mlogloss:0.76878
[11]	train-mlogloss:0.76366	eval-mlogloss:0.74684
[12]	train-mlogloss:0.74274	eval-mlogloss:0.72608
[13]	train-mlogloss:0.72213	eval-mlogloss:0.70423
[14]	train-mlogloss:0.70221	eval-mlogloss:0.68328
[15]	train-mlogloss:0.68226	eval-mlogloss:0.66212
[16]	train-mlogloss:0.66439	eval-mlogloss:0.64241
[17]	train-mlogloss:0.64735	eval-mlogloss:0.62403
[18]	train-mlogloss:0.62954	eval-mlogloss:0.60621
[19]	train-mlogloss:0.61317	eval-mlogloss:0.58868
[20]	train-mlogloss:0.59670	eval-mlogloss:0.57096
[21]	train-mlogloss:0.58155	eval-mlogloss:0.55492
[22]	train-mlogloss:0.56952	eval-mlogloss:0.54267
[23]	train-mlogloss:0.55538	eval-mlogloss:0.52833
[24]	train-mlogloss:0.54176	eval-mlogloss:0.51344
[25]	train-mlogloss:0.52805	eval-mlogloss:0.49930
[26]	train-mlogloss:0.51488	eval-mlogloss:0.48437
[27]	train-mlogloss:0.50162	eval-mlogloss:0.47036
[28]	train-mlogloss:0.48961	eval-mlogloss:0.45759
[29]	train-mlogloss:0.47759	eval-mlogloss:0.44484
[30]	train-mlogloss:0.46721	eval-mlogloss:0.43500
[31]	train-mlogloss:0.45637	eval-mlogloss:0.42317

[I 2026-09-18 14:49:14,581] Trial 38 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.05103	eval-mlogloss:1.05291
[1]	train-mlogloss:1.00354	eval-mlogloss:1.00245
[2]	train-mlogloss:0.96021	eval-mlogloss:0.95714
[3]	train-mlogloss:0.92090	eval-mlogloss:0.91378
[4]	train-mlogloss:0.88196	eval-mlogloss:0.87271
[5]	train-mlogloss:0.84660	eval-mlogloss:0.83617
[6]	train-mlogloss:0.81311	eval-mlogloss:0.80071
[7]	train-mlogloss:0.78085	eval-mlogloss:0.76684

[I 2026-09-18 14:49:14,624] Trial 39 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06567	eval-mlogloss:1.06848
[1]	train-mlogloss:1.02677	eval-mlogloss:1.02727
[2]	train-mlogloss:0.99076	eval-mlogloss:0.98884
[3]	train-mlogloss:0.95888	eval-mlogloss:0.95433
[4]	train-mlogloss:0.92574	eval-mlogloss:0.91978
[5]	train-mlogloss:0.89647	eval-mlogloss:0.88909
[6]	train-mlogloss:0.86899	eval-mlogloss:0.86059
[7]	train-mlogloss:0.84701	eval-mlogloss:0.83852
[8]	train-mlogloss:0.82047	eval-mlogloss:0.81025
[9]	train-mlogloss:0.79373	eval-mlogloss:0.78132
[10]	train-mlogloss:0.76782	eval-mlogloss:0.75344
[11]	train-mlogloss:0.74445	eval-mlogloss:0.72800
[12]	train-mlogloss:0.72458	eval-mlogloss:0.70654
[13]	train-mlogloss:0.70600	eval-mlogloss:0.68647
[14]	train-mlogloss:0.68334	eval-mlogloss:0.66232
[15]	train-mlogloss:0.66294	eval-mlogloss:0.64129
[16]	train-mlogloss:0.64280	eval-mlogloss:0.61860
[17]	train-mlogloss:0.62400	eval-mlogloss:0.59836
[18]	train-mlogloss:0.60554	eval-mlogloss:0.57999
[19]	train-mlogloss:0.59016	eval-mlogloss:0.56465
[20]	train-mlogloss:0.57335	eval-mlogloss:0.54788
[21]	train-mlogloss:0.55676	eval-mlogloss:0.53016
[22]	train-mlogloss:0.54405	eval-mlogloss:0.51689
[23]	train-mlogloss:0.52916	eval-mlogloss:0.50148
[24]	train-mlogloss:0.51449	eval-mlogloss:0.48518
[25]	train-mlogloss:0.50009	eval-mlogloss:0.47031
[26]	train-mlogloss:0.48556	eval-mlogloss:0.45379
[27]	train-mlogloss:0.47176	eval-mlogloss:0.43929
[28]	train-mlogloss:0.45979	eval-mlogloss:0.42643
[29]	train-mlogloss:0.44755	eval-mlogloss:0.41313
[30]	train-mlogloss:0.43754	eval-mlogloss:0.40540
[31]	train-mlogloss:0.42615	eval-mlogloss:0.39354

[I 2026-09-18 14:49:14,785] Trial 40 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.08457	eval-mlogloss:1.08644
[1]	train-mlogloss:1.07035	eval-mlogloss:1.07124
[2]	train-mlogloss:1.05673	eval-mlogloss:1.05678
[3]	train-mlogloss:1.04347	eval-mlogloss:1.04263
[4]	train-mlogloss:1.03036	eval-mlogloss:1.02870
[5]	train-mlogloss:1.01769	eval-mlogloss:1.01579
[6]	train-mlogloss:1.00505	eval-mlogloss:1.00266
[7]	train-mlogloss:0.99264	eval-mlogloss:0.98955
[8]	train-mlogloss:0.98031	eval-mlogloss:0.97690
[9]	train-mlogloss:0.96823	eval-mlogloss:0.96431
[10]	train-mlogloss:0.95626	eval-mlogloss:0.95162
[11]	train-mlogloss:0.94534	eval-mlogloss:0.93984
[12]	train-mlogloss:0.93430	eval-mlogloss:0.92851
[13]	train-mlogloss:0.92288	eval-mlogloss:0.91696
[14]	train-mlogloss:0.91175	eval-mlogloss:0.90529
[15]	train-mlogloss:0.90053	eval-mlogloss:0.89341
[16]	train-mlogloss:0.89008	eval-mlogloss:0.88206
[17]	train-mlogloss:0.87981	eval-mlogloss:0.87083
[18]	train-mlogloss:0.86915	eval-mlogloss:0.86012
[19]	train-mlogloss:0.85909	eval-mlogloss:0.84953
[20]	train-mlogloss:0.84888	eval-mlogloss:0.83860
[21]	train-mlogloss:0.83917	eval-mlogloss:0.82846
[22]	train-mlogloss:0.83023	eval-mlogloss:0.81942
[23]	train-mlogloss:0.82100	eval-mlogloss:0.81042
[24]	train-mlogloss:0.81198	eval-mlogloss:0.80073
[25]	train-mlogloss:0.80267	eval-mlogloss:0.79117
[26]	train-mlogloss:0.79359	eval-mlogloss:0.78106
[27]	train-mlogloss:0.78431	eval-mlogloss:0.77125
[28]	train-mlogloss:0.77550	eval-mlogloss:0.76203
[29]	train-mlogloss:0.76672	eval-mlogloss:0.75297
[30]	train-mlogloss:0.75854	eval-mlogloss:0.74511
[31]	train-mlogloss:0.75015	eval-mlogloss:0.73617
[32]	train-mlogloss:0.74185	eval-mlogloss:0.72738
[33]	train-mlogloss:0.73372	eval-mlogloss:0.71870
[34]	train-mlogloss:0.72573	eval-mlogloss:0.71029
[35]	train-mlogloss:0.71772	eval-mlogloss:0.70169
[36]	train-mlogloss:0.71001	eval-mlogloss:0.69366
[37]	train-mlogloss:0.70219	eval-mlogloss:0.68517
[38]	train-mlogloss:0.69399	eval-mlogloss:0.67688
[39]	train-mlogloss:0.68635	eval-mlogloss:0.66925
[40]	train-mlogloss:0.67912	eval-mlogloss:0.66149
[41]	train-mlogloss:0.67186	eval-mlogloss:0.65394
[42]	train-mlogloss:0.66471	eval-mlogloss:0.64666
[43]	train-mlogloss:0.65785	eval-mlogloss:0.63925
[44]	train-mlogloss:0.65080	eval-mlogloss:0.63190
[45]	train-mlogloss:0.64372	eval-mlogloss:0.62439
[46]	train-mlogloss:0.63686	eval-mlogloss:0.61685
[47]	train-mlogloss:0.63007	eval-mlogloss:0.60998
[48]	train-mlogloss:0.62348	eval-mlogloss:0.60318
[49]	train-mlogloss:0.61706	eval-mlogloss:0.59662
[50]	train-mlogloss:0.61073	eval-mlogloss:0.58987
[51]	train-mlogloss:0.60426	eval-mlogloss:0.58285
[52]	train-mlogloss:0.59796	eval-mlogloss:0.57595
[53]	train-mlogloss:0.59182	eval-mlogloss:0.56950
[54]	train-mlogloss:0.58535	eval-mlogloss:0.56269
[55]	train-mlogloss:0.57913	eval-mlogloss:0.55582
[56]	train-mlogloss:0.57317	eval-mlogloss:0.54933
[57]	train-mlogloss:0.56732	eval-mlogloss:0.54328
[58]	train-mlogloss:0.56137	eval-mlogloss:0.53705
[59]	train-mlogloss:0.55550	eval-mlogloss:0.53102
[60]	train-mlogloss:0.54989	eval-mlogloss:0.52491
[61]	train-mlogloss:0.54422	eval-mlogloss:0.51902
[62]	train-mlogloss:0.53885	eval-mlogloss:0.51323
[63]	train-mlogloss:0.53364	eval-mlogloss:0.50770
[64]	train-mlogloss:0.52814	eval-mlogloss:0.50256
[65]	train-mlogloss:0.52306	eval-mlogloss:0.49702
[66]	train-mlogloss:0.51811	eval-mlogloss:0.49168
[67]	train-mlogloss:0.51275	eval-mlogloss:0.48589
[68]	train-mlogloss:0.50765	eval-mlogloss:0.48042
[69]	train-mlogloss:0.50245	eval-mlogloss:0.47551
[70]	train-mlogloss:0.49749	eval-mlogloss:0.47112
[71]	train-mlogloss:0.49258	eval-mlogloss:0.46583
[72]	train-mlogloss:0.48789	eval-mlogloss:0.46090
[73]	train-mlogloss:0.48329	eval-mlogloss:0.45588
[74]	train-mlogloss:0.47862	eval-mlogloss:0.45095
[75]	train-mlogloss:0.47403	eval-mlogloss:0.44629
[76]	train-mlogloss:0.46947	eval-mlogloss:0.44139
[77]	train-mlogloss:0.46508	eval-mlogloss:0.43656
[78]	train-mlogloss:0.46046	eval-mlogloss:0.43159
[79]	train-mlogloss:0.45593	eval-mlogloss:0.42667
[80]	train-mlogloss:0.45201	eval-mlogloss:0.42241
[81]	train-mlogloss:0.44782	eval-mlogloss:0.41796
[82]	train-mlogloss:0.44349	eval-mlogloss:0.41368
[83]	train-mlogloss:0.43923	eval-mlogloss:0.41003
[84]	train-mlogloss:0.43501	eval-mlogloss:0.40574
[85]	train-mlogloss:0.43100	eval-mlogloss:0.40181
[86]	train-mlogloss:0.42719	eval-mlogloss:0.39805
[87]	train-mlogloss:0.42295	eval-mlogloss:0.39432
[88]	train-mlogloss:0.41904	eval-mlogloss:0.39004
[89]	train-mlogloss:0.41514	eval-mlogloss:0.38593
[90]	train-mlogloss:0.41117	eval-mlogloss:0.38155
[91]	train-mlogloss:0.40781	eval-mlogloss:0.37824
[92]	train-mlogloss:0.40407	eval-mlogloss:0.37436
[93]	train-mlogloss:0.40025	eval-mlogloss:0.37033
[94]	train-mlogloss:0.39648	eval-mlogloss:0.36696
[95]	train-mlogloss:0.39295	eval-mlogloss:0.36328
[96]	train-mlogloss:0.38929	eval-mlogloss:0.35921
[97]	train-mlogloss:0.38573	eval-mlogloss:0.35566
[98]	train-mlogloss:0.38248	eval-mlogloss:0.35203
[99]	train-mlogloss:0.37908	eval-mlogloss:0.34832
[100]	train-mlogloss:0.37555	eval-mlogloss:0.34442
[101]	train-mlogloss:0.37214	eval-mlogloss:0.34152
[102]	train-mlogloss:0.36856	eval-mlogloss:0.33778
[103]	train-mlogloss:0.36537	eval-mlogloss:0.33424
[104]	train-mlogloss:0.36194	eval-mlogloss:0.33089
[105]	train-mlogloss:0.35871	eval-mlogloss:0.32728
[106]	train-mlogloss:0.35565	eval-mlogloss:0.32404
[107]	train-mlogloss:0.35274	eval-mlogloss:0.32116
[108]	train-mlogloss:0.34967	eval-mlogloss:0.31775
[109]	train-mlogloss:0.34671	eval-mlogloss:0.31474
[110]	train-mlogloss:0.34361	eval-mlogloss:0.31139
[111]	train-mlogloss:0.34048	eval-mlogloss:0.30797
[112]	train-mlogloss:0.33727	eval-mlogloss:0.30495
[113]	train-mlogloss:0.33432	eval-mlogloss:0.30153
[114]	train-mlogloss:0.33144	eval-mlogloss:0.29890
[115]	train-mlogloss:0.32866	eval-mlogloss:0.29612
[116]	train-mlogloss:0.32574	eval-mlogloss:0.29289
[117]	train-mlogloss:0.32290	eval-mlogloss:0.28997
[118]	train-mlogloss:0.32008	eval-mlogloss:0.28749
[119]	train-mlogloss:0.31739	eval-mlogloss:0.28466
[120]	train-mlogloss:0.31462	eval-mlogloss:0.28164
[121]	train-mlogloss:0.31209	eval-mlogloss:0.27869
[122]	train-mlogloss:0.30936	eval-mlogloss:0.27601
[123]	train-mlogloss:0.30683	eval-mlogloss:0.27332
[124]	train-mlogloss:0.30412	eval-mlogloss:0.27044
[125]	train-mlogloss:0.30147	eval-mlogloss:0.26791
[126]	train-mlogloss:0.29896	eval-mlogloss:0.26525
[127]	train-mlogloss:0.29609	eval-mlogloss:0.26299
[128]	train-mlogloss:0.29370	eval-mlogloss:0.26041
[129]	train-mlogloss:0.29163	eval-mlogloss:0.25817
[130]	train-mlogloss:0.28907	eval-mlogloss:0.25559
[131]	train-mlogloss:0.28661	eval-mlogloss:0.25300
[132]	train-mlogloss:0.28409	eval-mlogloss:0.25020
[133]	train-mlogloss:0.28156	eval-mlogloss:0.24788
[134]	train-mlogloss:0.27922	eval-mlogloss:0.24533
[135]	train-mlogloss:0.27702	eval-mlogloss:0.24302
[136]	train-mlogloss:0.27458	eval-mlogloss:0.24068
[137]	train-mlogloss:0.27236	eval-mlogloss:0.23820
[138]	train-mlogloss:0.27000	eval-mlogloss:0.23590
[139]	train-mlogloss:0.26781	eval-mlogloss:0.23385
[140]	train-mlogloss:0.26566	eval-mlogloss:0.23162
[141]	train-mlogloss:0.26351	eval-mlogloss:0.22939
[142]	train-mlogloss:0.26141	eval-mlogloss:0.22728
[143]	train-mlogloss:0.25928	eval-mlogloss:0.22502
[144]	train-mlogloss:0.25719	eval-mlogloss:0.22271
[145]	train-mlogloss:0.25510	eval-mlogloss:0.22065
[146]	train-mlogloss:0.25303	eval-mlogloss:0.21859
[147]	train-mlogloss:0.25093	eval-mlogloss:0.21663
[148]	train-mlogloss:0.24907	eval-mlogloss:0.21446
[149]	train-mlogloss:0.24698	eval-mlogloss:0.21227
[150]	train-mlogloss:0.24491	eval-mlogloss:0.21022
[151]	train-mlogloss:0.24313	eval-mlogloss:0.20840
[152]	train-mlogloss:0.24114	eval-mlogloss:0.20634
[153]	train-mlogloss:0.23912	eval-mlogloss:0.20433
[154]	train-mlogloss:0.23735	eval-mlogloss:0.20264
[155]	train-mlogloss:0.23536	eval-mlogloss:0.20063
[156]	train-mlogloss:0.23342	eval-mlogloss:0.19851
[157]	train-mlogloss:0.23165	eval-mlogloss:0.19667
[158]	train-mlogloss:0.22990	eval-mlogloss:0.19468
[159]	train-mlogloss:0.22813	eval-mlogloss:0.19266
[160]	train-mlogloss:0.22633	eval-mlogloss:0.19071
[161]	train-mlogloss:0.22454	eval-mlogloss:0.18877
[162]	train-mlogloss:0.22278	eval-mlogloss:0.18674
[163]	train-mlogloss:0.22111	eval-mlogloss:0.18499
[164]	train-mlogloss:0.21926	eval-mlogloss:0.18369
[165]	train-mlogloss:0.21765	eval-mlogloss:0.18195
[166]	train-mlogloss:0.21604	eval-mlogloss:0.18035
[167]	train-mlogloss:0.21456	eval-mlogloss:0.17886
[168]	train-mlogloss:0.21304	eval-mlogloss:0.17709
[169]	train-mlogloss:0.21142	eval-mlogloss:0.17526
[170]	train-mlogloss:0.20976	eval-mlogloss:0.17385
[171]	train-mlogloss:0.20816	eval-mlogloss:0.17220
[172]	train-mlogloss:0.20663	eval-mlogloss:0.17053
[173]	train-mlogloss:0.20505	eval-mlogloss:0.16880
[174]	train-mlogloss:0.20349	eval-mlogloss:0.16726
[175]	train-mlogloss:0.20192	eval-mlogloss:0.16566
[176]	train-mlogloss:0.20060	eval-mlogloss:0.16422
[177]	train-mlogloss:0.19918	eval-mlogloss:0.16267
[178]	train-mlogloss:0.19778	eval-mlogloss:0.16124
[179]	train-mlogloss:0.19637	eval-mlogloss:0.15962
[180]	train-mlogloss:0.19511	eval-mlogloss:0.15831
[181]	train-mlogloss:0.19363	eval-mlogloss:0.15703
[182]	train-mlogloss:0.19236	eval-mlogloss:0.15571
[183]	train-mlogloss:0.19095	eval-mlogloss:0.15438
[184]	train-mlogloss:0.18955	eval-mlogloss:0.15301
[185]	train-mlogloss:0.18823	eval-mlogloss:0.15192
[186]	train-mlogloss:0.18693	eval-mlogloss:0.15037
[187]	train-mlogloss:0.18563	eval-mlogloss:0.14912
[188]	train-mlogloss:0.18429	eval-mlogloss:0.14782
[189]	train-mlogloss:0.18304	eval-mlogloss:0.14656
[190]	train-mlogloss:0.18174	eval-mlogloss:0.14520
[191]	train-mlogloss:0.18031	eval-mlogloss:0.14395
[192]	train-mlogloss:0.17906	eval-mlogloss:0.14281
[193]	train-mlogloss:0.17789	eval-mlogloss:0.14148
[194]	train-mlogloss:0.17665	eval-mlogloss:0.14042
[195]	train-mlogloss:0.17543	eval-mlogloss:0.13894
[196]	train-mlogloss:0.17416	eval-mlogloss:0.13782
[197]	train-mlogloss:0.17302	eval-mlogloss:0.13656
[198]	train-mlogloss:0.17188	eval-mlogloss:0.13538
[199]	train-mlogloss:0.17067	eval-mlogloss:0.13410
[200]	train-mlogloss:0.16951	eval-mlogloss:0.13274
[201]	train-mlogloss:0.16825	eval-mlogloss:0.13150
[202]	train-mlogloss:0.16725	eval-mlogloss:0.13032
[203]	train-mlogloss:0.16603	eval-mlogloss:0.12921
[204]	train-mlogloss:0.16482	eval-mlogloss:0.12788
[205]	train-mlogloss:0.16378	eval-mlogloss:0.12695
[206]	train-mlogloss:0.16274	eval-mlogloss:0.12592
[207]	train-mlogloss:0.16158	eval-mlogloss:0.12506
[208]	train-mlogloss:0.16047	eval-mlogloss:0.12389
[209]	train-mlogloss:0.15945	eval-mlogloss:0.12311
[210]	train-mlogloss:0.15846	eval-mlogloss:0.12205
[211]	train-mlogloss:0.15751	eval-mlogloss:0.12106
[212]	train-mlogloss:0.15637	eval-mlogloss:0.11996
[213]	train-mlogloss:0.15532	eval-mlogloss:0.11887
[214]	train-mlogloss:0.15436	eval-mlogloss:0.11824
[215]	train-mlogloss:0.15342	eval-mlogloss:0.11730
[216]	train-mlogloss:0.15236	eval-mlogloss:0.11649
[217]	train-mlogloss:0.15142	eval-mlogloss:0.11556
[218]	train-mlogloss:0.15036	eval-mlogloss:0.11448
[219]	train-mlogloss:0.14945	eval-mlogloss:0.11336
[220]	train-mlogloss:0.14863	eval-mlogloss:0.11233
[221]	train-mlogloss:0.14766	eval-mlogloss:0.11155
[222]	train-mlogloss:0.14686	eval-mlogloss:0.11051
[223]	train-mlogloss:0.14596	eval-mlogloss:0.10959
[224]	train-mlogloss:0.14507	eval-mlogloss:0.10852
[225]	train-mlogloss:0.14413	eval-mlogloss:0.10748
[226]	train-mlogloss:0.14318	eval-mlogloss:0.10661
[227]	train-mlogloss:0.14224	eval-mlogloss:0.10589
[228]	train-mlogloss:0.14138	eval-mlogloss:0.10503
[229]	train-mlogloss:0.14058	eval-mlogloss:0.10403
[230]	train-mlogloss:0.13971	eval-mlogloss:0.10334
[231]	train-mlogloss:0.13883	eval-mlogloss:0.10246
[232]	train-mlogloss:0.13794	eval-mlogloss:0.10155
[233]	train-mlogloss:0.13713	eval-mlogloss:0.10056
[234]	train-mlogloss:0.13634	eval-mlogloss:0.10002
[235]	train-mlogloss:0.13549	eval-mlogloss:0.09940
[236]	train-mlogloss:0.13475	eval-mlogloss:0.09851
[237]	train-mlogloss:0.13389	eval-mlogloss:0.09752
[238]	train-mlogloss:0.13302	eval-mlogloss:0.09666
[239]	train-mlogloss:0.13217	eval-mlogloss:0.09570
[240]	train-mlogloss:0.13146	eval-mlogloss:0.09484
[241]	train-mlogloss:0.13075	eval-mlogloss:0.09410
[242]	train-mlogloss:0.13012	eval-mlogloss:0.09362
[243]	train-mlogloss:0.12934	eval-mlogloss:0.09274
[244]	train-mlogloss:0.12863	eval-mlogloss:0.09194
[245]	train-mlogloss:0.12785	eval-mlogloss:0.09117
[246]	train-mlogloss:0.12717	eval-mlogloss:0.09040
[247]	train-mlogloss:0.12649	eval-mlogloss:0.08960
[248]	train-mlogloss:0.12578	eval-mlogloss:0.08878
[249]	train-mlogloss:0.12526	eval-mlogloss:0.08823
[250]	train-mlogloss:0.12466	eval-mlogloss:0.08762
[251]	train-mlogloss:0.12396	eval-mlogloss:0.08684
[252]	train-mlogloss:0.12332	eval-mlogloss:0.08626
[253]	train-mlogloss:0.12260	eval-mlogloss:0.08537
[254]	train-mlogloss:0.12192	eval-mlogloss:0.08470
[255]	train-mlogloss:0.12135	eval-mlogloss:0.08400
[256]	train-mlogloss:0.12063	eval-mlogloss:0.08329
[257]	train-mlogloss:0.11992	eval-mlogloss:0.08279
[258]	train-mlogloss:0.11918	eval-mlogloss:0.08192
[259]	train-mlogloss:0.11845	eval-mlogloss:0.08131
[260]	train-mlogloss:0.11771	eval-mlogloss:0.08052
[261]	train-mlogloss:0.11701	eval-mlogloss:0.07978
[262]	train-mlogloss:0.11638	eval-mlogloss:0.07907
[263]	train-mlogloss:0.11573	eval-mlogloss:0.07834
[264]	train-mlogloss:0.11497	eval-mlogloss:0.07780
[265]	train-mlogloss:0.11430	eval-mlogloss:0.07725
[266]	train-mlogloss:0.11367	eval-mlogloss:0.07659
[267]	train-mlogloss:0.11311	eval-mlogloss:0.07618
[268]	train-mlogloss:0.11254	eval-mlogloss:0.07549
[269]	train-mlogloss:0.11194	eval-mlogloss:0.07493
[270]	train-mlogloss:0.11133	eval-mlogloss:0.07425
[271]	train-mlogloss:0.11080	eval-mlogloss:0.07363
[272]	train-mlogloss:0.11036	eval-mlogloss:0.07309
[273]	train-mlogloss:0.10979	eval-mlogloss:0.07247
[274]	train-mlogloss:0.10936	eval-mlogloss:0.07210
[275]	train-mlogloss:0.10877	eval-mlogloss:0.07159
[276]	train-mlogloss:0.10817	eval-mlogloss:0.07093
[277]	train-mlogloss:0.10772	eval-mlogloss:0.07030
[278]	train-mlogloss:0.10728	eval-mlogloss:0.06979
[279]	train-mlogloss:0.10685	eval-mlogloss:0.06929
[280]	train-mlogloss:0.10648	eval-mlogloss:0.06881
[281]	train-mlogloss:0.10589	eval-mlogloss:0.06827
[282]	train-mlogloss:0.10543	eval-mlogloss:0.06798
[283]	train-mlogloss:0.10493	eval-mlogloss:0.06759
[284]	train-mlogloss:0.10442	eval-mlogloss:0.06697
[285]	train-mlogloss:0.10398	eval-mlogloss:0.06658
[286]	train-mlogloss:0.10355	eval-mlogloss:0.06599
[287]	train-mlogloss:0.10309	eval-mlogloss:0.06542
[288]	train-mlogloss:0.10267	eval-mlogloss:0.06482
[289]	train-mlogloss:0.10221	eval-mlogloss:0.06433
[290]	train-mlogloss:0.10171	eval-mlogloss:0.06381
[291]	train-mlogloss:0.10123	eval-mlogloss:0.06333
[292]	train-mlogloss:0.10077	eval-mlogloss:0.06305
[293]	train-mlogloss:0.10039	eval-mlogloss:0.06258
[294]	train-mlogloss:0.09997	eval-mlogloss:0.06209
[295]	train-mlogloss:0.09956	eval-mlogloss:0.06169
[296]	train-mlogloss:0.09911	eval-mlogloss:0.06115
[297]	train-mlogloss:0.09868	eval-mlogloss:0.06058
[298]	train-mlogloss:0.09832	eval-mlogloss:0.06013
[299]	train-mlogloss:0.09790	eval-mlogloss:0.05975

[I 2026-09-18 14:49:16,055] Trial 41 finished with value: 1.0 and parameters: {'lambda': 0.15121140858794663, 'alpha': 1.0817782655318776e-06, 'eta': 0.010692510591399727, 'gamma': 0.01201922881744396, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.5087754238122925, 'colsample_bytree': 0.8308517175138882}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.06253	eval-mlogloss:1.06277
[1]	train-mlogloss:1.02582	eval-mlogloss:1.02379
[2]	train-mlogloss:0.99181	eval-mlogloss:0.98737
[3]	train-mlogloss:0.96003	eval-mlogloss:0.95285
[4]	train-mlogloss:0.92918	eval-mlogloss:0.92051
[5]	train-mlogloss:0.90030	eval-mlogloss:0.89074
[6]	train-mlogloss:0.87255	eval-mlogloss:0.86172
[7]	train-mlogloss:0.84554	eval-mlogloss:0.83338

[I 2026-09-18 14:49:16,109] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04893	eval-mlogloss:1.04993
[1]	train-mlogloss:1.00043	eval-mlogloss:0.99806
[2]	train-mlogloss:0.95567	eval-mlogloss:0.95073
[3]	train-mlogloss:0.91346	eval-mlogloss:0.90613
[4]	train-mlogloss:0.87470	eval-mlogloss:0.86488
[5]	train-mlogloss:0.83851	eval-mlogloss:0.82796
[6]	train-mlogloss:0.80534	eval-mlogloss:0.79363
[7]	train-mlogloss:0.77263	eval-mlogloss:0.75929

[I 2026-09-18 14:49:16,164] Trial 43 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04327	eval-mlogloss:1.04111
[1]	train-mlogloss:0.97466	eval-mlogloss:0.96851

[I 2026-09-18 14:49:16,193] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06906	eval-mlogloss:1.06941
[1]	train-mlogloss:1.03853	eval-mlogloss:1.03700
[2]	train-mlogloss:1.01113	eval-mlogloss:1.00750
[3]	train-mlogloss:0.98441	eval-mlogloss:0.97830
[4]	train-mlogloss:0.95784	eval-mlogloss:0.95045
[5]	train-mlogloss:0.93300	eval-mlogloss:0.92485
[6]	train-mlogloss:0.90903	eval-mlogloss:0.89965
[7]	train-mlogloss:0.88548	eval-mlogloss:0.87492
[8]	train-mlogloss:0.86265	eval-mlogloss:0.85068
[9]	train-mlogloss:0.84099	eval-mlogloss:0.82788
[10]	train-mlogloss:0.81976	eval-mlogloss:0.80607
[11]	train-mlogloss:0.80150	eval-mlogloss:0.78665
[12]	train-mlogloss:0.78264	eval-mlogloss:0.76747
[13]	train-mlogloss:0.76349	eval-mlogloss:0.74746
[14]	train-mlogloss:0.74508	eval-mlogloss:0.72779
[15]	train-mlogloss:0.72702	eval-mlogloss:0.70883
[16]	train-mlogloss:0.71017	eval-mlogloss:0.69011
[17]	train-mlogloss:0.69389	eval-mlogloss:0.67221
[18]	train-mlogloss:0.67664	eval-mlogloss:0.65488
[19]	train-mlogloss:0.66098	eval-mlogloss:0.63812
[20]	train-mlogloss:0.64541	eval-mlogloss:0.62149
[21]	train-mlogloss:0.63079	eval-mlogloss:0.60604
[22]	train-mlogloss:0.61900	eval-mlogloss:0.59415
[23]	train-mlogloss:0.60468	eval-mlogloss:0.58043
[24]	train-mlogloss:0.59122	eval-mlogloss:0.56580
[25]	train-mlogloss:0.57807	eval-mlogloss:0.55220
[26]	train-mlogloss:0.56529	eval-mlogloss:0.53771
[27]	train-mlogloss:0.55244	eval-mlogloss:0.52424
[28]	train-mlogloss:0.54079	eval-mlogloss:0.51229
[29]	train-mlogloss:0.52882	eval-mlogloss:0.49956
[30]	train-mlogloss:0.51774	eval-mlogloss:0.48816
[31]	train-mlogloss:0.50650	eval-mlogloss:0.47628

[I 2026-09-18 14:49:16,360] Trial 45 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.02320	eval-mlogloss:1.02090
[1]	train-mlogloss:0.95134	eval-mlogloss:0.94410

[I 2026-09-18 14:49:16,397] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05785	eval-mlogloss:1.05777
[1]	train-mlogloss:1.01654	eval-mlogloss:1.01384
[2]	train-mlogloss:0.97928	eval-mlogloss:0.97370
[3]	train-mlogloss:0.94411	eval-mlogloss:0.93513
[4]	train-mlogloss:0.90921	eval-mlogloss:0.89899
[5]	train-mlogloss:0.87677	eval-mlogloss:0.86549
[6]	train-mlogloss:0.84637	eval-mlogloss:0.83274
[7]	train-mlogloss:0.81789	eval-mlogloss:0.80210

[I 2026-09-18 14:49:16,464] Trial 47 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06727	eval-mlogloss:1.06900
[1]	train-mlogloss:1.03513	eval-mlogloss:1.03487
[2]	train-mlogloss:1.00527	eval-mlogloss:1.00365
[3]	train-mlogloss:0.97726	eval-mlogloss:0.97301
[4]	train-mlogloss:0.94925	eval-mlogloss:0.94341
[5]	train-mlogloss:0.92331	eval-mlogloss:0.91665
[6]	train-mlogloss:0.89836	eval-mlogloss:0.89040
[7]	train-mlogloss:0.87388	eval-mlogloss:0.86474
[8]	train-mlogloss:0.85030	eval-mlogloss:0.83961
[9]	train-mlogloss:0.82792	eval-mlogloss:0.81606
[10]	train-mlogloss:0.80594	eval-mlogloss:0.79346
[11]	train-mlogloss:0.78569	eval-mlogloss:0.77206
[12]	train-mlogloss:0.76619	eval-mlogloss:0.75222
[13]	train-mlogloss:0.74622	eval-mlogloss:0.73186
[14]	train-mlogloss:0.72752	eval-mlogloss:0.71246
[15]	train-mlogloss:0.70896	eval-mlogloss:0.69281
[16]	train-mlogloss:0.69176	eval-mlogloss:0.67349
[17]	train-mlogloss:0.67498	eval-mlogloss:0.65509
[18]	train-mlogloss:0.65736	eval-mlogloss:0.63744
[19]	train-mlogloss:0.64144	eval-mlogloss:0.62037
[20]	train-mlogloss:0.62562	eval-mlogloss:0.60305
[21]	train-mlogloss:0.61058	eval-mlogloss:0.58720
[22]	train-mlogloss:0.59797	eval-mlogloss:0.57431
[23]	train-mlogloss:0.58354	eval-mlogloss:0.56052
[24]	train-mlogloss:0.56990	eval-mlogloss:0.54561
[25]	train-mlogloss:0.55662	eval-mlogloss:0.53174
[26]	train-mlogloss:0.54376	eval-mlogloss:0.51719
[27]	train-mlogloss:0.53087	eval-mlogloss:0.50361
[28]	train-mlogloss:0.51896	eval-mlogloss:0.49137
[29]	train-mlogloss:0.50688	eval-mlogloss:0.47861
[30]	train-mlogloss:0.49579	eval-mlogloss:0.46708
[31]	train-mlogloss:0.48426	eval-mlogloss:0.45542

[I 2026-09-18 14:49:16,631] Trial 48 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.07351	eval-mlogloss:1.07387
[1]	train-mlogloss:1.04797	eval-mlogloss:1.04671
[2]	train-mlogloss:1.02456	eval-mlogloss:1.02173
[3]	train-mlogloss:1.00183	eval-mlogloss:0.99665
[4]	train-mlogloss:0.97876	eval-mlogloss:0.97243
[5]	train-mlogloss:0.95740	eval-mlogloss:0.95063
[6]	train-mlogloss:0.93669	eval-mlogloss:0.92890
[7]	train-mlogloss:0.91697	eval-mlogloss:0.90821
[8]	train-mlogloss:0.89686	eval-mlogloss:0.88686
[9]	train-mlogloss:0.87770	eval-mlogloss:0.86638
[10]	train-mlogloss:0.85859	eval-mlogloss:0.84552
[11]	train-mlogloss:0.84157	eval-mlogloss:0.82717
[12]	train-mlogloss:0.82529	eval-mlogloss:0.81008
[13]	train-mlogloss:0.80796	eval-mlogloss:0.79179
[14]	train-mlogloss:0.79162	eval-mlogloss:0.77493
[15]	train-mlogloss:0.77488	eval-mlogloss:0.75745
[16]	train-mlogloss:0.75943	eval-mlogloss:0.74053
[17]	train-mlogloss:0.74443	eval-mlogloss:0.72434
[18]	train-mlogloss:0.72854	eval-mlogloss:0.70829
[19]	train-mlogloss:0.71431	eval-mlogloss:0.69310
[20]	train-mlogloss:0.69966	eval-mlogloss:0.67741
[21]	train-mlogloss:0.68569	eval-mlogloss:0.66307
[22]	train-mlogloss:0.67343	eval-mlogloss:0.64976
[23]	train-mlogloss:0.66062	eval-mlogloss:0.63570
[24]	train-mlogloss:0.64828	eval-mlogloss:0.62198
[25]	train-mlogloss:0.63596	eval-mlogloss:0.60929
[26]	train-mlogloss:0.62360	eval-mlogloss:0.59547
[27]	train-mlogloss:0.61145	eval-mlogloss:0.58316
[28]	train-mlogloss:0.60023	eval-mlogloss:0.57073
[29]	train-mlogloss:0.58841	eval-mlogloss:0.55803
[30]	train-mlogloss:0.57829	eval-mlogloss:0.54800
[31]	train-mlogloss:0.56774	eval-mlogloss:0.53656

[I 2026-09-18 14:49:16,801] Trial 49 pruned. Trial was pruned at iteration 32.

Best trial: {'lambda': 0.00432232676269759, 'alpha': 1.7219063672366305e-05, 'eta': 0.12831722446825466, 'gamma': 0.00015260127947542152, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6695314840050257, 'colsample_bytree': 0.7364141600688288}
Best accuracy: 1.0